"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { Achievement, Character, NovelProject, ProjectBackup, StoryBible, TimelineEvent, World, WorldRule, WritingTask } from "@/lib/novel-ai/domain";
import { createNovelRepository } from "@/lib/novel-ai/repository";
import { backupDownload, createProjectBackup, markdownDownload, validateBackupPayload } from "@/lib/novel-ai/repository/backup";
import { RELEASE_MANIFEST } from "@/lib/release-manifest";
import ProjectNavigation from "./project-navigation";

type Section = "characters" | "world" | "timeline" | "story-bible" | "tasks" | "achievements" | "backups";
type Data = { project: NovelProject | null; characters: Character[]; worlds: World[]; rules: WorldRule[]; timeline: TimelineEvent[]; bibles: StoryBible[]; tasks: WritingTask[]; achievements: Achievement[]; backups: ProjectBackup[] };
const titles: Record<Section, [string, string]> = { characters: ["角色", "查看作品中的人物與目前狀態。"], world: ["世界設定", "保存故事背景、規則與重要地點。"], timeline: ["時間線", "整理故事中已發生的重要事件。"], "story-bible": ["故事設定", "作品記憶會在作者確認後逐步更新。"], tasks: ["任務", "追蹤目前正在推進的創作目標。"], achievements: ["成就", "記錄完成的重要創作里程碑。"], backups: ["備份與還原", "建立、下載、匯入與還原這本作品。"] };

export default function ProjectSectionClient({ projectId, section }: { projectId: string; section: Section }) {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState("");
  async function load() { try { const repo = createNovelRepository(); setData({ project: await repo.get("projects", projectId), characters: await repo.list("characters", projectId), worlds: await repo.list("worlds", projectId), rules: await repo.list("worldRules", projectId), timeline: await repo.list("timeline", projectId), bibles: await repo.list("storyBibles", projectId), tasks: await repo.list("tasks", projectId), achievements: await repo.list("achievements", projectId), backups: await repo.list("backups", projectId) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "資料載入失敗"); } }
  useEffect(() => { void load(); }, [projectId]);
  if (error) return <main className="p2ProjectShell"><p>資料載入失敗，請重新嘗試。</p><button onClick={() => void load()}>重新載入</button></main>;
  if (!data) return <main className="p2ProjectShell"><p>正在載入作品資料…</p></main>;
  const [title, desc] = titles[section];
  return <main className="p2ProjectShell"><header><Link href="/studio">我的作品</Link><div><small>{data.project?.title || "未命名作品"}</small><h1>{title}</h1></div><span>本機保存</span></header><ProjectNavigation projectId={projectId} active={section}/><section className="p2ProjectSection"><header><h2>{title}</h2><p>{desc}</p></header><SectionBody section={section} data={data} onChanged={load}/></section></main>;
}

function Empty({ children }: { children: React.ReactNode }) { return <div className="p2DataEmpty"><p>{children}</p><span>你可以稍後再補充，這不會阻礙作品繼續創作。</span></div>; }
function SectionBody({ section, data, onChanged }: { section: Section; data: Data; onChanged: () => Promise<void> }) {
  if (section === "characters") return data.characters.length ? <div className="p2DataGrid">{data.characters.map((item) => <article key={item.id}><b>{item.name}</b><span>{item.identity.value || "尚未設定身分"}</span><p>{item.goal.value || "尚未設定目標"}</p></article>)}</div> : <Empty>目前還沒有角色資料。</Empty>;
  if (section === "world") return data.worlds.length || data.rules.length ? <><div className="p2DataGrid">{data.worlds.map((item) => <article key={item.id}><b>{item.name.value || "未命名世界"}</b><p>{item.summary.value || "尚未建立世界說明"}</p></article>)}</div><div className="p2DataList">{data.rules.map((item) => <article key={item.id}><b>{item.title}</b><p>{item.description}</p></article>)}</div></> : <Empty>目前尚未建立世界設定。現實題材也可以保持空白。</Empty>;
  if (section === "timeline") return data.timeline.length ? <div className="p2DataList">{data.timeline.map((item) => <article key={item.id}><time>{item.storyTime || "未設定時間"}</time><b>{item.title}</b><p>{item.summary}</p></article>)}</div> : <Empty>目前還沒有時間線事件。</Empty>;
  if (section === "story-bible") return data.bibles.length ? <div className="p2DataList">{data.bibles.map((item) => <article key={item.id}><b>作品故事設定</b><p>未解劇情 {item.unresolvedThreads.length} 項，世界規則 {item.worldRuleIds.length} 項，角色 {item.characterIds.length} 位。</p><small>版本 {item.revision}</small></article>)}</div> : <Empty>目前還沒有已確認的故事設定。</Empty>;
  if (section === "tasks") return data.tasks.length ? <div className="p2DataList">{data.tasks.map((item) => <article key={item.id}><b>{item.title}</b><p>{item.progress} / {item.target}，{item.status === "completed" ? "已完成" : "進行中"}</p></article>)}</div> : <Empty>目前沒有任務。</Empty>;
  if (section === "achievements") return data.achievements.length ? <div className="p2DataGrid">{data.achievements.map((item) => <article key={item.id}><b>{item.title}</b><p>{item.progress} / {item.target}</p></article>)}</div> : <Empty>完成創作後，成就會出現在這裡。</Empty>;
  return <BackupCenter projectId={data.project?.id || ""} title={data.project?.title || "作品"} backups={data.backups} onChanged={onChanged}/>;
}

function BackupCenter({ projectId, title, backups, onChanged }: { projectId: string; title: string; backups: ProjectBackup[]; onChanged: () => Promise<void> }) {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function create(kind: ProjectBackup["kind"], shouldDownload = false) { if (busy) return; setBusy(true); setMessage("正在整理作品、閱讀進度與故事設定…"); try { const repo = createNovelRepository(); const { backup, payload } = await createProjectBackup(repo, projectId, kind, { appCommit: RELEASE_MANIFEST.appCommit, releaseTag: RELEASE_MANIFEST.releaseTag }); if (shouldDownload) backupDownload(payload, title); setMessage(`備份完成，大小約 ${Math.max(1, Math.round(backup.byteSize / 1024))} KB。`); await onChanged(); } catch { setMessage("備份失敗，原有作品資料仍然安全。"); } finally { setBusy(false); } }
  async function importFile(file: File) { if (busy) return; setBusy(true); setMessage("正在驗證備份檔…"); try { const check = await validateBackupPayload(JSON.parse(await file.text())); if (!check.valid) { setMessage(`匯入失敗：${check.reason}`); return; } const repo = createNovelRepository(); await createProjectBackup(repo, projectId, "safety", { appCommit: RELEASE_MANIFEST.appCommit, releaseTag: RELEASE_MANIFEST.releaseTag }); const copyId = await repo.importProject(check.payload.records, "copy"); setMessage("已匯入為新作品，原作品沒有被修改。"); location.assign(`/studio/project/${copyId}/write`); } catch { setMessage("匯入失敗，原有作品資料仍然安全。"); } finally { setBusy(false); } }
  async function restore(backup: ProjectBackup) { if (!backup.manifest) { setMessage("這是舊版建立時的快照，無法直接還原。請先建立一份新的完整備份。 "); return; } if (busy || !confirm("會先建立目前作品的安全備份，再還原這份備份。要繼續嗎？")) return; setBusy(true); try { const repo = createNovelRepository(); await createProjectBackup(repo, projectId, "safety", { appCommit: RELEASE_MANIFEST.appCommit, releaseTag: RELEASE_MANIFEST.releaseTag }); await repo.importProject(backup.snapshot as Record<string, unknown[]>, "replace", projectId); setMessage("已完成還原，正在重新載入作品。"); setTimeout(() => location.reload(), 300); } catch { setMessage("還原失敗，已保留還原前的安全備份。"); } finally { setBusy(false); } }
  async function exportMarkdown() { try { const repo = createNovelRepository(); markdownDownload(await repo.exportProject(projectId), title); setMessage("已下載可閱讀的 Markdown 正文。"); } catch { setMessage("正文匯出失敗，原有作品資料仍然安全。"); } }
  return <section className="p2BackupCenter"><header><h2>作品備份</h2><p>作品目前主要保存在這個瀏覽器中。建議定期下載一份完整備份。</p></header><div className="p2BackupActions"><button disabled={busy} onClick={() => void create("quick", true)}>立即備份並下載</button><button disabled={busy} onClick={() => void create("full", true)}>完整備份並下載</button><button disabled={busy} onClick={() => void exportMarkdown()}>匯出 Markdown 正文</button><label className="buttonLike">匯入作品備份<input type="file" hidden accept="application/json,.json,.novel-backup.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importFile(file); }}/></label></div>{message && <p role="status">{message}</p>}<div className="p2DataList">{backups.length ? backups.map((backup) => <article key={backup.id}><b>{backup.kind === "full" ? "完整備份" : backup.kind === "safety" ? "還原前安全備份" : backup.kind === "initial" ? "建立作品時的備份" : "快速備份"}</b><time>{new Date(backup.createdAt).toLocaleString("zh-TW")}</time><p>{Math.max(1, Math.round(backup.byteSize / 1024))} KB</p><div><button disabled={busy || !backup.manifest} onClick={() => backup.manifest && backupDownload({ manifest: backup.manifest, records: backup.snapshot as Record<string, unknown[]> }, title)}>下載</button><button disabled={busy || !backup.manifest} onClick={() => void restore(backup)}>還原</button></div></article>) : <Empty>這本作品目前還沒有備份。建立第一份備份，可以避免瀏覽器資料遺失。</Empty>}</div></section>;
}
