"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { Achievement, Character, NovelProject, ProjectBackup, StoryBible, TimelineEvent, World, WorldRule, WritingTask } from "@/lib/novel-ai/domain";
import { createNovelRepository } from "@/lib/novel-ai/repository";
import ProjectNavigation from "./project-navigation";

type Section = "characters"|"world"|"timeline"|"story-bible"|"tasks"|"achievements"|"backups";
type Data = { project:NovelProject|null; characters:Character[]; worlds:World[]; rules:WorldRule[]; timeline:TimelineEvent[]; bibles:StoryBible[]; tasks:WritingTask[]; achievements:Achievement[]; backups:ProjectBackup[] };
const titles:Record<Section,[string,string]>={characters:["角色","查看人物資料與成長線索"],world:["世界","整理世界背景與規則"],timeline:["時間線","依故事順序查看事件"],"story-bible":["故事記憶","作者確認後的長期設定"],tasks:["任務","追蹤寫作與故事目標"],achievements:["成就","記錄創作里程碑"],backups:["備份","保護作品與版本"]};
export default function ProjectSectionClient({projectId,section}:{projectId:string;section:Section}){const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{void(async()=>{try{const r=createNovelRepository();setData({project:await r.get("projects",projectId),characters:await r.list("characters",projectId),worlds:await r.list("worlds",projectId),rules:await r.list("worldRules",projectId),timeline:await r.list("timeline",projectId),bibles:await r.list("storyBibles",projectId),tasks:await r.list("tasks",projectId),achievements:await r.list("achievements",projectId),backups:await r.list("backups",projectId)})}catch(e){setError(e instanceof Error?e.message:"讀取失敗")}})()},[projectId]);if(error)return <main className="p2ProjectShell"><p>資料載入失敗：{error}</p></main>;if(!data)return <main className="p2ProjectShell"><p>正在讀取作品……</p></main>;const [title,desc]=titles[section];return <main className="p2ProjectShell"><header><Link href="/studio">← 我的作品</Link><div><small>{data.project?.title||"作品"}</small><h1>{title}</h1></div><span>本機作品資料</span></header><ProjectNavigation projectId={projectId} active={section}/><section className="p2ProjectSection"><header><h2>{title}</h2><p>{desc}</p></header><SectionBody section={section} data={data}/></section></main>}
function Empty({children}:{children:React.ReactNode}){return <div className="p2DataEmpty"><p>{children}</p><span>你可以先保持空白，寫作過程中再逐步補充。</span></div>}
function SectionBody({section,data}:{section:Section;data:Data}){
 if(section==="characters")return data.characters.length?<div className="p2DataGrid">{data.characters.map(c=><article key={c.id}><b>{c.name}</b><span>{c.identity.value||"身分尚未設定"}</span><p>{c.goal.value||"目標稍後補充"}</p></article>)}</div>:<Empty>目前還沒有角色資料。</Empty>;
 if(section==="world")return data.worlds.length||data.rules.length?<><div className="p2DataGrid">{data.worlds.map(w=><article key={w.id}><b>{w.name.value||"未命名世界"}</b><p>{w.summary.value||"背景稍後補充"}</p></article>)}</div><div className="p2DataList">{data.rules.map(r=><article key={r.id}><b>{r.title}</b><p>{r.description}</p></article>)}</div></>:<Empty>目前尚未建立特殊世界設定；現實題材也可以不設定。</Empty>;
 if(section==="timeline")return data.timeline.length?<div className="p2DataList">{data.timeline.map(e=><article key={e.id}><time>{e.storyTime||"時間未定"}</time><b>{e.title}</b><p>{e.summary}</p></article>)}</div>:<Empty>目前沒有已確認的時間線事件。</Empty>;
 if(section==="story-bible")return data.bibles.length?<div className="p2DataList">{data.bibles.map(b=><article key={b.id}><b>正式故事記憶</b><p>未解事件 {b.unresolvedThreads.length} 項，世界規則 {b.worldRuleIds.length} 項，人物 {b.characterIds.length} 位。</p><small>版本 {b.revision}</small></article>)}</div>:<Empty>目前沒有正式故事記憶。</Empty>;
 if(section==="tasks")return data.tasks.length?<div className="p2DataList">{data.tasks.map(t=><article key={t.id}><b>{t.title}</b><p>{t.progress}／{t.target} · {t.status==="completed"?"已完成":"進行中"}</p></article>)}</div>:<Empty>目前沒有任務。</Empty>;
 if(section==="achievements")return data.achievements.length?<div className="p2DataGrid">{data.achievements.map(a=><article key={a.id}><b>{a.title}</b><p>{a.progress}／{a.target}</p></article>)}</div>:<Empty>繼續創作後，成就會在達成條件時出現。</Empty>;
 return data.backups.length?<div className="p2DataList">{data.backups.map(b=><article key={b.id}><b>{b.kind==="initial"?"建立作品時的安全備份":"作品備份"}</b><time>{new Date(b.createdAt).toLocaleString("zh-TW")}</time><p>{Math.max(1,Math.round(b.byteSize/1024))} KB</p></article>)}</div>:<Empty>這本作品目前還沒有備份。</Empty>;
}
