"use client";

import { useEffect, useMemo, useState } from "react";
import type { ChangeEvent } from "react";
import Link from "next/link";

type Screen = "home" | "create" | "write" | "choice" | "inspect" | "library";
type Wizard = { genre:string; name:string; identity:string; personality:string; goal:string; weakness:string; ability:string; location:string; rule:string; factions:string; crisis:string; playMode:string; title:string; synopsis:string };
type Project = { id:string; title:string; genre:string; protagonist:string; identity:string; goal:string; location:string; rule:string; conflict:string; playMode:string; chapterTitle:string; draft:string; updatedAt:string; versions:Array<{at:string; title:string; content:string}> };
type Candidate = { task:string; title:string; content:string; source:string; createdAt:string } | null;
type Choice = { key:string; text:string; impact:string; stat:"stamina"|"experience"|"reputation"; delta:number };
type StudioState = { schemaVersion:number; activeProjectId:string; projects:Project[]; wizard:Wizard; wizardStep:number; candidate:Candidate; stats:Record<string,number>; branches:Array<{choice:string; stats:Record<string,number>; at:string}> };

const STORAGE_KEY="novel_p11r2_studio_state";
const LEGACY_KEY="novel_p11_consumer_state";
const emptyWizard:Wizard={genre:"",name:"",identity:"",personality:"",goal:"",weakness:"",ability:"",location:"",rule:"",factions:"",crisis:"",playMode:"一般小說",title:"",synopsis:""};
const initialState:StudioState={schemaVersion:2,activeProjectId:"",projects:[],wizard:{...emptyWizard},wizardStep:1,candidate:null,stats:{stamina:100,money:0,affection:0,reputation:0,experience:0,level:1,turns:0,questProgress:0},branches:[]};
const genres=["玄幻修仙","都市異能","戀愛養成","宮廷權謀","商戰經營","RPG 冒險","成人故事","自訂故事"];
const playModes=["一般小說","三選一互動","RPG 冒險","戀愛養成","商戰經營","成人互動"];
const tasks=[
  ["create_story","AI 推薦故事設定","整理可採用的故事方向"],
  ["story_seed","產生故事種子","建立可延伸的故事起點"],
  ["plan_chapter","產生十章大綱","規劃接下來十章的推進"],
  ["first_chapter","建立第一章","建立第一章候選稿"],
  ["continue_story","續寫下一章","承接目前正文續寫"],
  ["rewrite_scene","改寫選取段落","保留原文提供改寫候選"],
  ["fix_conflicts","檢查前後矛盾","列出衝突與修正方向"],
  ["diagnose_story","找出未回收伏筆","整理尚待處理的故事承諾"],
] as const;

function words(text:string){return (text.match(/[\u4e00-\u9fff]/g)||[]).length+(text.replace(/[\u4e00-\u9fff]/g," ").match(/\b[\w'-]+\b/g)||[]).length}
function formatTime(value:string){return value?new Date(value).toLocaleString("zh-TW"):"尚未儲存"}
function migrate():StudioState {
  try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null"); if(saved?.schemaVersion===2)return {...initialState,...saved,wizard:{...emptyWizard,...saved.wizard}} } catch {}
  try { const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||"null"); if(old){const projects=(old.projects||[]).map((p:Record<string,unknown>)=>({id:String(p.id||crypto.randomUUID()),title:String(p.title||"未命名作品"),genre:String(p.genre||""),protagonist:String(p.protagonist||"主角"),identity:"",goal:"",location:String(p.world||""),rule:"",conflict:String(p.conflict||""),playMode:String(p.playMode||"一般小說"),chapterTitle:String(p.chapterTitle||"第一章"),draft:String(p.text||""),updatedAt:String(p.updatedAt||new Date().toISOString()),versions:[]}));return {...initialState,projects,activeProjectId:String(old.activeProjectId||projects[0]?.id||""),wizard:{...emptyWizard,...old.wizard,name:old.wizard?.protagonistName||""}}} } catch {}
  return initialState;
}

export default function StudioClient({initialScreen,initialTask,release}:{initialScreen:string;initialTask:string;release:Record<string,string>}){
  const [screen,setScreen]=useState<Screen>(initialScreen as Screen);
  const [state,setState]=useState<StudioState>(initialState);
  const [loaded,setLoaded]=useState(false);
  const [menuOpen,setMenuOpen]=useState(false);
  const [selectedChoice,setSelectedChoice]=useState("A");
  const [customChoice,setCustomChoice]=useState("");
  const project=useMemo(()=>state.projects.find(p=>p.id===state.activeProjectId)||state.projects[0]||null,[state.projects,state.activeProjectId]);
  useEffect(()=>{const timer=setTimeout(()=>{setState(migrate());setLoaded(true)},0);return()=>clearTimeout(timer)},[]);
  useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEY,JSON.stringify(state))},[state,loaded]);
  useEffect(()=>{const url=new URL(location.href);url.searchParams.set("screen",screen);history.replaceState({},"",url)},[screen]);
  useEffect(()=>{if(initialTask&&loaded&&project){runTask(initialTask)}},[loaded]); // eslint-disable-line react-hooks/exhaustive-deps
  function update(partial:Partial<StudioState>){setState(value=>({...value,...partial}))}
  function updateWizard(field:keyof Wizard,value:string){setState(s=>({...s,wizard:{...s.wizard,[field]:value}}))}
  function navigate(value:Screen){setScreen(value);setMenuOpen(false)}
  function createProject(){const w=state.wizard;const now=new Date().toISOString();const id=crypto.randomUUID();const title=w.title||`${w.name||"主角"}的${w.genre||"新故事"}`;const draft=`# ${title}\n\n## 第一章\n\n${w.name||"主角"}在${w.location||"陌生的世界"}醒來，眼前最迫切的危機是${w.crisis||"尚未揭露的威脅"}。\n\n這個世界遵守一條不能忽略的規則：${w.rule||"每個選擇都會留下後果"}。為了${w.goal||"完成自己的目標"}，角色必須先做出第一個決定。`;const next:Project={id,title,genre:w.genre,protagonist:w.name||"主角",identity:w.identity,goal:w.goal,location:w.location,rule:w.rule,conflict:w.crisis,playMode:w.playMode,chapterTitle:"第一章",draft,updatedAt:now,versions:[]};update({projects:[next,...state.projects],activeProjectId:id,candidate:null});navigate("write")}
  function saveDraft(title:string,draft:string){if(!project)return;const now=new Date().toISOString();setState(s=>({...s,projects:s.projects.map(p=>p.id===project.id?{...p,chapterTitle:title,draft,updatedAt:now}:p)}))}
  function runTask(task:string){const p=project;const label=tasks.find(item=>item[0]===task)?.[1]||"故事協助";const name=p?.protagonist||state.wizard.name||"主角";const conflict=p?.conflict||state.wizard.crisis||"眼前問題";const recent=(p?.draft||"").slice(-500);const contents:Record<string,string>={create_story:`${name}的核心目標是「${p?.goal||state.wizard.goal||"尚待確定"}」。建議讓「${conflict}」在第一章直接形成可見壓力，並保留一個能延伸長篇的秘密。`,story_seed:`${name}發現一項足以改變現況的線索，但取得線索會觸犯「${p?.rule||state.wizard.rule||"世界規則"}」。第一個選擇將決定盟友是否願意同行。`,plan_chapter:Array.from({length:10},(_,i)=>`第${i+1}章：${i<3?"建立危機與人物承諾":i<7?"擴大衝突並揭露代價":"回收線索並製造新懸念"}`).join("\n"),first_chapter:`${name}在${p?.location||"故事起點"}察覺異常。${conflict}比預期更早爆發，迫使角色在資訊不足時採取行動。`,continue_story:`${recent?"承接目前段落：\n"+recent+"\n\n":""}${name}沒有立即回答，而是先確認最容易被忽略的細節。這個遲疑讓對手露出破綻，也讓${conflict}進入下一個階段。`,rewrite_scene:`改寫候選：保留原事件結果，增加角色動作、環境反應與對話停頓，使${name}的選擇更具體。`,fix_conflicts:`檢查結果：請確認「${p?.rule||"尚未設定的世界規則"}」是否在目前章節得到遵守；目前未自動改動正文。`,diagnose_story:`待處理承諾：${conflict}；角色目標：${p?.goal||"尚未設定"}。建議下一章至少推進其中一項。`};setState(s=>({...s,candidate:{task,title:label,content:contents[task]||contents.continue_story,source:"本機故事智慧規則・讀取目前作品與最近正文・外部請求 0",createdAt:new Date().toISOString()}}));if(screen!=="write")navigate("write")}
  function acceptCandidate(){if(!project||!state.candidate)return;const old={at:new Date().toISOString(),title:project.chapterTitle,content:project.draft};setState(s=>({...s,candidate:null,projects:s.projects.map(p=>p.id===project.id?{...p,draft:`${p.draft}\n\n${s.candidate?.content||""}`.trim(),updatedAt:new Date().toISOString(),versions:[old,...p.versions]}:p)}))}
  function choices():Choice[]{const name=project?.protagonist||"主角",conflict=project?.conflict||"目前危機";return[{key:"A",text:`${name}主動面對${conflict}，迫使對手立即回應。`,impact:"主線推進較快，但體力下降。",stat:"stamina",delta:-8},{key:"B",text:`${name}先調查最近線索，再決定是否公開行動。`,impact:"風險較低，經驗值提升。",stat:"experience",delta:12},{key:"C",text:`${name}利用第三方製造轉折，引誘對手暴露底牌。`,impact:"聲望提升，但關係可能受損。",stat:"reputation",delta:6}]}
  function confirmChoice(){const option=choices().find(c=>c.key===selectedChoice)||choices()[0],text=customChoice||option.text;const before={...state.stats};setState(s=>({...s,branches:[...s.branches,{choice:text,stats:before,at:new Date().toISOString()}],stats:{...s.stats,[option.stat]:Math.max(0,(s.stats[option.stat]||0)+option.delta),turns:(s.stats.turns||0)+1},candidate:{task:"branch_choice",title:"故事分支候選",content:`${text}\n\n這個決定將改變下一個場景，但尚未覆蓋正式正文。`,source:"本機動態選項・Candidate 安全邊界・外部請求 0",createdAt:new Date().toISOString()}}));navigate("write")}
  function undoBranch(){const last=state.branches.at(-1);if(!last)return;update({branches:state.branches.slice(0,-1),stats:last.stats,candidate:null})}
  const navItems:Array<[Screen,string]>=[["home","首頁"],["create","開始創作"],["write","繼續寫作"],["library","我的作品"],["write","修改作品"],["inspect","檢查作品"],["choice","互動故事"]];
  return <div className="studioShell" data-consumer-release={release.consumerRelease} data-app-commit={release.appCommit}>
    <button className="studioMenuButton" type="button" onClick={()=>setMenuOpen(true)} aria-label="開啟導覽選單">☰</button>
    <aside className={`studioRail ${menuOpen?"open":""}`} aria-label="消費者創作導航"><Link className="studioBrand" href="/"><b>諸天萬界</b><span>小說生成系統</span></Link><button className="studioCreate" onClick={()=>navigate("create")}>＋ 建立新作品</button><nav>{navItems.map(([id,label],index)=><button key={`${id}-${index}`} className={screen===id?"active":""} onClick={()=>navigate(id)}>{label}</button>)}</nav><Link className="studioProfessional" href="/professional">專業工具</Link></aside>
    {menuOpen&&<button className="studioScrim" type="button" aria-label="關閉導覽選單" onClick={()=>setMenuOpen(false)}/>} 
    <div className="studioMain"><header className="studioTop"><Link href="/">諸天萬界小說生成系統</Link><nav><button onClick={()=>navigate("home")}>首頁</button><button onClick={()=>navigate("create")}>創作</button><button onClick={()=>navigate("write")}>AI 助手</button><button onClick={()=>navigate("choice")}>互動故事</button></nav><span>一般模式</span></header><main className="studioContent">{screen==="home"&&<HomeScreen project={project} navigate={navigate} runTask={runTask}/>} {screen==="create"&&<CreateScreen state={state} updateWizard={updateWizard} setStep={step=>update({wizardStep:step})} createProject={createProject} runTask={runTask}/>} {(screen==="write"||screen==="inspect")&&<WriteScreen key={project?.id||"empty"} project={project} candidate={state.candidate} navigate={navigate} saveDraft={saveDraft} runTask={runTask} acceptCandidate={acceptCandidate} discard={()=>update({candidate:null})}/>} {screen==="choice"&&<ChoiceScreen project={project} choices={choices()} selected={selectedChoice} setSelected={setSelectedChoice} custom={customChoice} setCustom={setCustomChoice} confirm={confirmChoice} undo={undoBranch} canUndo={state.branches.length>0}/>} {screen==="library"&&<LibraryScreen projects={state.projects} open={id=>{update({activeProjectId:id});navigate("write")}}/>}</main></div>
  </div>
}

function HomeScreen({project,navigate,runTask}:{project:Project|null;navigate:(s:Screen)=>void;runTask:(t:string)=>void}){return <section className="studioHome"><div className="studioWelcome"><div><span>歡迎回來</span><h1>今天想創作什麼故事？</h1><p>從一個想法開始，作品與候選稿會保存在目前裝置。</p></div><div><button className="gold" onClick={()=>navigate("create")}>建立新故事</button><button onClick={()=>navigate("write")}>繼續最近作品</button><button onClick={()=>runTask("create_story")}>AI 幫我想故事</button><button onClick={()=>navigate("choice")}>玩互動故事</button></div></div><h2>最近作品</h2>{project?<article className="studioRecent"><div>{project.title.slice(0,2)}</div><section><small>{project.genre}</small><h3>{project.title}</h3><p>{project.chapterTitle}・{words(project.draft)} 字・{formatTime(project.updatedAt)}</p><button onClick={()=>navigate("write")}>繼續創作</button></section></article>:<div className="studioEmpty"><b>尚未建立作品</b><p>建立第一部小說後，最近進度會出現在這裡。</p><button onClick={()=>navigate("create")}>建立第一部小說</button></div>}<h2>快速功能</h2><div className="studioQuick">{[["continue_story","寫下一章"],["rewrite_scene","修改一段文字"],["fix_conflicts","檢查前後矛盾"],["diagnose_story","找出未回收伏筆"]].map(([id,label])=><button key={id} onClick={()=>runTask(id)}>{label}</button>)}</div></section>}

function CreateScreen({state,updateWizard,setStep,createProject,runTask}:{state:StudioState;updateWizard:(f:keyof Wizard,v:string)=>void;setStep:(s:number)=>void;createProject:()=>void;runTask:(t:string)=>void}){const w=state.wizard,step=state.wizardStep;const input=(field:keyof Wizard,label:string)=><label>{label}<input value={w[field]} onChange={e=>updateWizard(field,e.target.value)}/></label>;return <section className="studioWizard"><header><span>建立新作品</span><h1>{["","你想寫什麼故事？","建立主角","建立故事世界","選擇故事玩法","預覽並建立"][step]}</h1><p>第 {step} 步，共 5 步</p></header><div className="studioSteps">{[1,2,3,4,5].map(i=><i className={i<=step?"done":""} key={i}/>)}</div><div className="studioWizardBody">{step===1&&<div className="studioGenreGrid">{genres.map(g=><button key={g} className={w.genre===g?"active":""} onClick={()=>updateWizard("genre",g)}><b>{g}</b><span>{g==="成人故事"?"僅限成年使用者主動開啟":"建立這類故事"}</span></button>)}</div>}{step===2&&<><div className="studioForm">{input("name","主角是誰")}{input("identity","主角的身分")}{input("personality","主角的個性")}{input("goal","主角最想得到什麼")}{input("weakness","主角最大的弱點")}{input("ability","主角有什麼特殊能力")}</div><button onClick={()=>runTask("create_story")}>AI 幫我推薦</button></>}{step===3&&<div className="studioForm">{input("location","故事發生在哪裡")}{input("rule","這個世界有什麼特別規則")}{input("factions","有哪些重要勢力")}{input("crisis","最大危機是什麼")}</div>}{step===4&&<div className="studioGenreGrid">{playModes.map(m=><button key={m} className={w.playMode===m?"active":""} onClick={()=>updateWizard("playMode",m)}><b>{m}</b><span>{m.includes("RPG")?"等級・經驗值・體力・任務":m.includes("戀愛")?"好感度・信任度・關係":m.includes("商戰")?"金錢・收入・聲望・資產":"標準長篇創作"}</span></button>)}</div>}{step===5&&<><div className="studioForm">{input("title","暫定書名")}<label>故事簡介<textarea value={w.synopsis} onChange={(e:ChangeEvent<HTMLTextAreaElement>)=>updateWizard("synopsis",e.target.value)}/></label></div><dl className="studioPreview"><div><dt>主角簡介</dt><dd>{w.name||"尚未設定"}・{w.identity||"尚未設定"}</dd></div><div><dt>世界背景</dt><dd>{w.location||"尚未設定"}</dd></div><div><dt>核心衝突</dt><dd>{w.crisis||"尚未設定"}</dd></div><div><dt>故事玩法</dt><dd>{w.playMode}</dd></div></dl><details><summary>更多故事設定</summary><p>分類包、主題大類、細分類、故事引擎、主角原型、故事裝置、世界核心、能力核心、主要衝突、反派核心與敘事風格可在專業工具中繼續編輯，並使用相同作品資料。</p><a href="/professional">開啟完整進階設定</a></details></>}</div><footer><button disabled={step===1} onClick={()=>setStep(Math.max(1,step-1))}>返回修改</button>{step<5?<button className="gold" onClick={()=>setStep(step+1)}>下一步</button>:<><button onClick={()=>runTask("create_story")}>AI 幫我完善</button><button className="gold" onClick={createProject}>建立作品並寫第一章</button></>}</footer></section>}

function WriteScreen({project,candidate,navigate,saveDraft,runTask,acceptCandidate,discard}:{project:Project|null;candidate:Candidate;navigate:(s:Screen)=>void;saveDraft:(t:string,d:string)=>void;runTask:(t:string)=>void;acceptCandidate:()=>void;discard:()=>void}){const [title,setTitle]=useState(project?.chapterTitle||"第一章"),[draft,setDraft]=useState(project?.draft||"");if(!project)return <div className="studioEmpty"><b>此作品尚未建立章節</b><p>先建立作品，才能開始寫作。</p><button onClick={()=>navigate("create")}>建立第一部小說</button></div>;return <section className="studioWriting"><aside><h2>{project.title}</h2><p>{project.genre}</p><nav><button>章節列表</button><button>故事設定</button><button>主要角色</button><button>世界觀</button><button onClick={()=>runTask("diagnose_story")}>伏筆與線索</button><button>故事時間線</button><button>任務與成就</button><button>故事數值</button><button>版本紀錄</button></nav></aside><main><header><label>目前章節<input value={title} onChange={e=>setTitle(e.target.value)}/></label><span>本機自動保存</span></header><textarea aria-label="正文編輯器" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="從這裡開始寫你的故事……"/><footer><span>{words(draft)} 字</span><div><button>上一章</button><button>下一章</button><button>新增章節</button><button onClick={()=>runTask("continue_story")}>AI 幫我續寫</button><button onClick={()=>runTask("rewrite_scene")}>修改選取內容</button><button className="gold" onClick={()=>saveDraft(title,draft)}>儲存草稿</button></div></footer></main><aside className="studioAssistant"><header><span>AI 創作助手</span><h2>你想讓系統幫什麼？</h2></header><div className="studioTaskGrid">{tasks.map(([id,label,desc])=><button key={id} onClick={()=>runTask(id)}><b>{label}</b><span>{desc}</span></button>)}</div>{candidate&&<article className="studioCandidate"><header><b>{candidate.title}</b><span>候選稿・尚未修改正式正文</span></header><pre>{candidate.content}</pre><small>{candidate.source}</small><footer><button className="gold" onClick={acceptCandidate}>採用並建立版本</button><button onClick={discard}>放棄</button></footer></article>}</aside></section>}

function ChoiceScreen({project,choices,selected,setSelected,custom,setCustom,confirm,undo,canUndo}:{project:Project|null;choices:Choice[];selected:string;setSelected:(s:string)=>void;custom:string;setCustom:(s:string)=>void;confirm:()=>void;undo:()=>void;canUndo:boolean}){return <section className="studioChoice"><header><span>三選一互動</span><h1>你準備怎麼做？</h1><p>{project?"選項已讀取目前作品、人物與衝突。":"建立作品後，系統會讀取目前故事產生三個選擇。"}</p></header><div>{choices.map(c=><button key={c.key} className={selected===c.key?"active":""} onClick={()=>setSelected(c.key)}><b>{c.key}. {c.text}</b><span>可能影響：{c.impact}</span></button>)}</div><label>自己決定<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="輸入你的行動"/></label><footer><button className="gold" onClick={confirm}>建立故事分支候選</button>{canUndo&&<button onClick={undo}>回到上一個選擇點</button>}</footer></section>}

function LibraryScreen({projects,open}:{projects:Project[];open:(id:string)=>void}){return <section className="studioLibrary"><header><span>我的作品</span><h1>作品與存檔</h1></header>{projects.length?<div>{projects.map(p=><article key={p.id}><div>{p.title.slice(0,2)}</div><section><h2>{p.title}</h2><p>{p.genre}・{words(p.draft)} 字・{formatTime(p.updatedAt)}</p><button onClick={()=>open(p.id)}>繼續寫作</button></section></article>)}</div>:<div className="studioEmpty"><b>尚未建立作品</b><p>作品會保存在目前瀏覽器。</p></div>}</section>}
