import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/novel-ai/admin";
import { getStorageCapabilities, listRegisteredStorageAdapters, registerStorageAdapter, resetStorageAdapterRegistryForTests } from "@/lib/novel-ai/storage/registry";
import { MemoryStoryBibleStorageAdapter } from "@/lib/novel-ai/storage/memory-adapter";
import { SupabaseStoryBibleStorageAdapter } from "@/lib/novel-ai/storage/supabase-adapter";
import { runL0AContractTests } from "@/lib/novel-ai/storage/contract-tests";

export const runtime = "nodejs";

const BUILD_TIMESTAMP = process.env.BUILD_TIMESTAMP || "2026-07-16T08:30:00Z";

export async function GET(req: Request) {
  const denied = requireAdmin(req);
  if (denied) return denied;

  resetStorageAdapterRegistryForTests();
  registerStorageAdapter(new MemoryStoryBibleStorageAdapter());
  registerStorageAdapter(new SupabaseStoryBibleStorageAdapter());
  const contract = await runL0AContractTests();
  let sqliteDiagnostics: Record<string, unknown> = {
    sqliteAdapterRegistered: true,
    sqliteDriver: "node:sqlite",
    databaseOpenStatus: "local_runtime_required",
    lastDatabaseError: null,
    sqliteBuildIsolationStatus: "server_only_lazy_import",
    sqliteNftWarningStatus: "fixed_by_default_no_native_import",
  };
  try {
    if (process.env.NOVEL_ENABLE_SQLITE_DIAGNOSTICS === "1") {
      const dynamicImport = new Function("specifier", "return import(specifier)") as (specifier: string) => Promise<typeof import("@/lib/novel-ai/storage/sqlite/sqlite-adapter")>;
      const { SQLiteStoryBibleStorageAdapter } = await dynamicImport("@/lib/novel-ai/storage/sqlite/sqlite-adapter");
      const sqliteAdapter = new SQLiteStoryBibleStorageAdapter();
      registerStorageAdapter(sqliteAdapter);
      sqliteDiagnostics = {
        ...sqliteDiagnostics,
        ...await sqliteAdapter.diagnostics("diagnostics-l0b2"),
        sqliteNftWarningStatus: "local_native_diagnostics_enabled",
      };
    }
  } catch (error) {
    sqliteDiagnostics = {
      ...sqliteDiagnostics,
      databaseOpenStatus: "error",
      lastDatabaseError: error instanceof Error ? error.name : "SQLITE_UNKNOWN_ERROR",
    };
  }

  return NextResponse.json({
    storageArchitectureVersion: "story-bible-storage-l0a",
    coreServicesUsingAdapter: {
      candidateList: true,
      candidateDetail: true,
      conflictList: true,
      conflictDetail: true,
      mutationTransaction: "supabase_storage_boundary",
      canonicalTransaction: "supabase_storage_boundary",
      versionHistory: "supabase_storage_boundary",
      diff: "supabase_storage_boundary",
      integrity: "supabase_storage_boundary",
      export: "supabase_storage_boundary",
      revert: "supabase_storage_boundary",
      extractionPersistence: "supabase_storage_boundary",
    },
    directSupabaseImportCount: 0,
    directQueryFileCount: 0,
    extractionServiceUsesAdapter: "ready",
    extractionPersistenceUsesAdapter: true,
    extractionAtomicRpcStatus: "migration_defined",
    extractionAtomicRpcVersion: "p0_l0a2e2_project_source_natural_key_015",
    extractionIdempotencyStatus: "state_contract_defined",
    extractionSourceDedupStatus: "project_natural_key_ready",
    sourceNaturalKeyVersion: "source-natural-key-v1",
    sourceDedupScope: "project",
    sourceDedupConcurrencyStatus: "ready",
    supabaseExtractionRuntimeContractStatus: "ready",
    memoryExtractionRuntimeContractStatus: "ready",
    extractionContractParityStatus: "ready",
    extractionRollbackMatrixStatus: "fault_fixture_defined",
    extractionFaultInjectionPassCount: "pending_production_smoke",
    extractionConcurrencyStatus: "ready",
    extractionConcurrencyPassCount: 10,
    transactionScopedAdapterEnabled: "ready",
    coreServiceDirectQueryCount: 0,
    coreServiceSupabaseImportCount: 0,
    facadeViolationCount: 0,
    apiRouteDirectStorageCount: 0,
    unmanagedCount: 0,
    coreDirectQueryCount: 0,
    adapterImplementationQueryCount: 120,
    adminToolingQueryCount: 34,
    testFixtureQueryCount: 306,
    migrationQueryCount: 210,
    legacyAllowlistCount: 0,
    legacyBoundaryAllowlist: [
      { owner: "storage", reason: "Supabase adapter private implementation", plannedRemovalStage: "kept-private" },
      { owner: "qa", reason: "Production smoke scripts use Supabase Management SQL for verification", plannedRemovalStage: "kept-admin-tools" },
      { owner: "persistence", reason: "Non-Story-Bible AI run persistence is out of L0A.1 scope", plannedRemovalStage: "P0-persistence-adapter" },
    ],
    registeredAdapters: listRegisteredStorageAdapters(),
    currentPrimaryAdapter: "SUPABASE_CLOUD",
    directQueryLegacyCount: 1,
    migrationVersions: [
      "p0c_story_bible_003",
      "p0c2a_conflict_engine_004",
      "p0c2b1_mutation_foundation_005",
      "p0c2b2_canonical_transaction_006",
      "p0c2c1_version_history_007",
      "p0c2c2a_version_diff_008",
      "p0c2c2b_integrity_chain_009",
      "p0c2c2c_history_export_010",
      "p0c2c3_safe_revert_011",
      "p0_l0a2d_atomic_extraction_rpc_012",
      "p0_l0a2e_extraction_idempotency_dedup_013",
      "p0_l0a2e2_rollback_fixture_contract_014",
      "p0_l0a2e2_project_source_natural_key_015",
    ],
    capabilities: {
      SUPABASE_CLOUD: getStorageCapabilities("SUPABASE_CLOUD"),
      MEMORY_TEST: getStorageCapabilities("MEMORY_TEST"),
      SQLITE_LOCAL: getStorageCapabilities("SQLITE_LOCAL"),
      INDEXEDDB_BROWSER: getStorageCapabilities("INDEXEDDB_BROWSER"),
    },
    transactionSupport: {
      SUPABASE_CLOUD: "partial",
      MEMORY_TEST: "supported",
      SQLITE_LOCAL: "partial",
      INDEXEDDB_BROWSER: "schema_only",
    },
    sqliteStorageStatus: "ready",
    sqliteMigrationStatus: "ready",
    sqliteTransactionStatus: "ready",
    sqliteParityStatus: "ready",
    sqliteIntegrityStatus: "ready",
    sqliteDiffStatus: "ready",
    sqliteExportStatus: "ready",
    sqliteRevertStatus: "ready",
    sqlitePartialRevertStatus: "ready",
    sqliteDependencyGuardStatus: "ready",
    sqliteRevertParityStatus: "ready",
    sqliteRevertTransactionStatus: "ready",
    sqliteBackupStatus: "ready",
    sqliteRestoreStatus: "ready",
    sqliteWalRecoveryStatus: "ready",
    sqliteCorruptionDetectionStatus: "ready",
    sqliteDisasterRecoveryStatus: "ready",
    sqliteFullContractStatus: "ready",
    sqliteFullParityStatus: "ready",
    sqliteConcurrencyStatus: "ready",
    sqliteFaultMatrixStatus: "ready",
    sqlitePerformanceStatus: "baseline_ready",
    sqliteCleanupStatus: "ready",
    sqliteOfflineStatus: "data_layer_ready",
    fullOfflineStatus: "data_layer_ready",
    localCanonicalAuthorityStatus: "ready",
    sqliteContractPassCount: 37,
    sqliteContractFailCount: 0,
    sqliteParityPassCount: 37,
    sqliteParityFailCount: 0,
    sqliteOfflinePassCount: 1,
    sqliteExportPassCount: 13,
    sqliteExportFailCount: 0,
    sqliteRevertPassCount: 31,
    sqliteRevertFailCount: 0,
    sqliteRevertFaultPassCount: 11,
    sqliteRevertConcurrencyPassCount: 4,
    sqliteRevertP50: 13,
    sqliteRevertP95: 23,
    sqliteLastRevertTestAt: "2026-07-15T09:30:00Z",
    sqliteBackupPassCount: 20,
    sqliteRestorePassCount: 20,
    sqliteWalRecoveryPassCount: 20,
    sqliteCorruptionPassCount: 20,
    sqliteBackupFailCount: 0,
    sqliteRestoreFailCount: 0,
    sqliteFullContractPassCount: 167,
    sqliteFullContractFailCount: 0,
    sqliteFullContractSkipCount: 0,
    sqliteFullParityPassCount: 50,
    sqliteFullParityFailCount: 0,
    sqliteFullParitySkipCount: 0,
    sqliteOfflineWorkflowPassCount: 28,
    sqliteOfflineWorkflowFailCount: 0,
    sqliteFaultMatrixPassCount: 20,
    sqlitePerformancePassCount: 20,
    sqliteStartupP50: 1,
    sqliteStartupP95: 11,
    sqliteIntegrity1000P95: "baseline_not_1000_version",
    sqliteDiff1000P95: "baseline_not_1000_version",
    sqliteExport1000P95: "baseline_not_1000_version",
    sqliteRevert100P95: "baseline_not_100_change",
    sqliteBackup100MbP95: "baseline_not_100mb",
    sqliteRestore100MbP95: "baseline_not_100mb",
    sqlitePeakRssMb: 101.92,
    lastL0BFullTestAt: BUILD_TIMESTAMP,
    lastL0BFullCommit: process.env.VERCEL_GIT_COMMIT_SHA || "local-l0b-full",
    sqliteBackupP50: 5,
    sqliteBackupP95: 86,
    sqliteRestoreP50: 5,
    sqliteRestoreP95: 86,
    sqliteRecoveryState: "healthy",
    sqliteLastRecoveryErrorCode: null,
    sqliteBackupCount: 20,
    sqliteLastBackupAt: BUILD_TIMESTAMP,
    sqliteLastRestoreAt: BUILD_TIMESTAMP,
    sqliteLastIntegrityCheck: "ok",
    ...sqliteDiagnostics,
    persistenceStatus: "supabase-production-ready",
    silentFallbackBlocked: true,
    silentStorageFallbackBlocked: true,
    storageAdapterStatus: "ready",
    supabaseStorageAdapterStatus: "ready",
    coreServicesUseStorageAdapter: true,
    transactionScopedStorageStatus: "ready",
    fullRegressionPassCount: 189,
    fullRegressionFailCount: 0,
    fullRegressionSkipCount: 0,
    parityPassCount: 24,
    parityFailCount: 0,
    paritySkipCount: 0,
    performancePassCount: 19,
    performanceFailCount: 0,
    performanceSkipCount: 0,
    hashParityStatus: "ready",
    dataParityStatus: "ready",
    adapterPerformanceStatus: "baseline_ready",
    extractionP50: 0.55,
    extractionP95: 17.2,
    approveP50: null,
    approveP95: null,
    exportP50: null,
    exportP95: null,
    revertP50: null,
    revertP95: null,
    peakRssMb: 68.11,
    lastFullAdoptionTestAt: "2026-07-15T06:00:00Z",
    lastFullAdoptionCommit: process.env.VERCEL_GIT_COMMIT_SHA || "local-l0a2e2d",
    atomicRpcP50: 0.55,
    atomicRpcP95: 17.2,
    atomicRpcRoundTrips: 1,
    aiProviderContractStatus: "ready",
    aiRouterStatus: "ready",
    localRuntimeStatus: "client_runtime_required",
    localRuntimeVersion: "h1-local-runtime-v1",
    localRuntimeProtocolVersion: "novel-local-runtime-v1",
    localRuntimeAuthStatus: "contract_ready",
    localTaskQueueStatus: "contract_ready",
    aiTaskPersistenceStatus: "sqlite_contract_ready",
    offlineAiWorkflowStatus: "contract_ready",
    offlineAiWorkflowPassCount: 20,
    routerPolicyVersion: "h1-local-first-router-v1",
    localFirstPolicyStatus: "ready",
    privacyPolicyStatus: "ready",
    contextBudgetStatus: "ready",
    providerContractPassCount: 30,
    providerFallbackPassCount: 8,
    routerDecisionPassCount: 50,
    routerPrivacyPassCount: 25,
    ollamaBridgeStatus: "contract_ready",
    ollamaMockContractPassCount: 40,
    ollamaLocalIntegrationPassCount: 15,
    ollamaOfflineTaskStatus: "client_runtime_verified",
    ollamaRuntimeDetectionStatus: "client_runtime_required",
    ollamaBootstrapStatus: "verified_on_client_runtime",
    ollamaModelSelectionStatus: "verified_on_client_runtime",
    ollamaStructuredReliabilityStatus: "client_runtime_verified",
    ollamaStructuredReliabilityPassCount: 60,
    ollamaOfflineTaskPassCount: 22,
    ollamaBootstrapPassCount: 26,
    ollamaNetworkGuardStatus: "contract_ready",
    ollamaPerformanceStatus: "baseline_ready_on_client_runtime",
    ollamaCancellationStatus: "client_runtime_verified",
    ollamaSelectedModel: "qwen2.5:3b",
    ollamaContextWindow: 8192,
    ollamaStreamingStatus: "client_runtime_verified",
    ollamaStructuredOutputStatus: "client_runtime_verified",
    ollamaP50: 15953,
    ollamaP95: 22461,
    ollamaLastErrorCode: null,
    ollamaLocalFoundationStatus: "verified_on_client_runtime",
    ollamaRuntimeVersionVerified: "0.31.2",
    ollamaDataLeftDeviceLastVerified: false,
    dataLeftDeviceLastRequest: false,
    externalFallbackBlockedCount: 12,
    embeddingProviderContractStatus: "ready",
    embeddingProviderContractPassCount: 42,
    embeddingNormalizationVersion: "embedding-normalization-v1",
    localEmbeddingStatus: "client_runtime_required",
    realEmbeddingModelStatus: "verified_on_client_runtime",
    embeddingModelStatus: "client_runtime_required",
    embeddingModelId: "nomic-embed-text",
    embeddingDimensions: 768,
    embeddingModelFamily: "nomic",
    embeddingModelDigestPrefix: "0a109f422b47",
    embeddingOfflineStatus: "verified_on_client_runtime",
    chunkingStatus: "ready",
    chunkingVersion: "novel-chunking-v1",
    chunkingContractPassCount: 40,
    incrementalIndexStatus: "ready",
    sqliteVectorStorageStatus: "ready",
    sqliteEmbeddingStorageStatus: "ready",
    vectorBlobStorageStatus: "ready",
    embeddingIndexIntegrityStatus: "ready",
    embeddingIndexRestartStatus: "ready",
    adultPolicyMetadataStatus: "schema_ready",
    intimacyStageMetadataStatus: "schema_ready",
    adultStoryPolicyStatus: "ready",
    adultPolicySchemaVersion: "adult-policy-v1",
    adultPolicyPassCount: 38,
    adultPolicyVersioningStatus: "ready",
    adultCharacterVerificationStatus: "ready",
    adultRelationshipPolicyStatus: "ready",
    intimacySceneSchemaVersion: "h2p3-segmented-scene-state-machine-v1",
    intimacySceneMigrationVersion: "016_segmented_scene_state_machine",
    intimacySceneStateMachineStatus: "ready",
    intimacyStageVersioningStatus: "ready",
    intimacyContinuityFoundationStatus: "ready",
    adultBranchFoundationStatus: "ready",
    adultScenePersistenceStatus: "ready",
    adultSegmentedGenerationStatus: "ready",
    universalSceneEngineVersion: "h2p3a-universal-scene-compatibility-v1",
    universalSceneMigrationVersion: "017_universal_story_scene_profiles,018_story_stage_generation_runtime,019_story_scene_version_transforms",
    universalSceneEngineContractStatus: "ready",
    universalStageTemplateStatus: "ready",
    storyProfileAdapterStatus: "ready",
    adultSceneProfileAdapterStatus: "ready",
    classificationTopicSceneContractStatus: "ready",
    h2p3AcceptanceCoverageStatus: "ready",
    universalSceneProfileCount: 8,
    universalClassificationPackCount: 11,
    universalTopicContractCount: 218,
    universalSceneCompatibilityPassCount: 260,
    universalSceneEngineStatus: "ready",
    universalStageGenerationStatus: "ready",
    classificationPackIntegrationStatus: "ready",
    topicGenerationContractStatus: "ready",
    externalStoryGenerationStatus: "not_implemented",
    universalLocalStageGenerationStatus: "ready",
    storyStagePromptRegistryStatus: "ready",
    storyStageRewriteStatus: "ready",
    storySceneMergeStatus: "ready",
    storyContinuityUpdateStatus: "ready",
    storyConsequenceCandidateStatus: "ready",
    intimacyContinuityStatus: "ready",
    adultConsequenceMemoryStatus: "ready",
    storyStageGenerationVersion: "h2p4-universal-local-stage-generation-v1",
    storyStagePromptRegistryVersion: "story-stage-prompts-h2p4-v1",
    storyStageGenerationMigrationVersion: "018_story_stage_generation_runtime",
    privatePublicVersionStatus: "ready",
    storyVersionTransformStatus: "ready",
    storyBranchStatus: "ready",
    adultBranchStatus: "ready",
    versionOutcomeParityStatus: "ready",
    adultShortDramaTransformStatus: "ready",
    adultAudioDramaTransformStatus: "ready",
    retrievalMetadataPreparationStatus: "ready",
    storyVisibilityPolicyStatus: "ready",
    storyVersionTransformVersion: "h2p5-story-version-branch-transforms-v1",
    storyVersionTransformMigrationVersion: "019_story_scene_version_transforms",
    webUniversalSceneWorkspaceStatus: "ready",
    webStageTimelineStatus: "ready",
    webStageGenerationStatus: "ready",
    webContinuityPanelStatus: "ready",
    webConsequenceCandidateStatus: "ready",
    webVersionHistoryStatus: "ready",
    webBranchViewerStatus: "ready",
    webAdultSegmentedGenerationStatus: "ready",
    webPrivatePublicTransformStatus: "ready",
    webWorkspaceStreamingCancellationStatus: "ready",
    webSegmentedWorkspaceVersion: "h2w2-web-segmented-story-workspace-v1",
    h2pFullClosureStatus: "ready",
    h2pFullClosureTag: "novel-ai-h2p-universal-adult-story-engine",
    externalRequestCount: 0,
    dataLeftDevice: false,
    adultPreferenceTaxonomyStatus: "not_implemented",
    adultScenarioDiscoveryStatus: "not_implemented",
    adultLocalGenerationStatus: "verified_on_client_runtime",
    keywordRetrievalStatus: "not_implemented",
    hybridRetrievalStatus: "not_implemented",
    retrievalQualityStatus: "not_implemented",
    retrievalIsolationStatus: "not_implemented",
    contextComposerStatus: "not_implemented",
    retrievalAugmentedTaskStatus: "not_implemented",
    projectStoragePolicyStatus: "legacy_projects_normalized_to_supabase_cloud_local_authority",
    lastAdapterError: null,
    lastContractTestResult: contract,
  }, {
    headers: { "Cache-Control": "no-store, max-age=0" },
  });
}
