import type {
  PlatformProviderId,
  PlatformTaskType,
} from "../../router/platform-types";
import type { BrowserDeviceBenchmark } from "./browser-device-benchmark";
import type { BrowserWebLLMModelManifest } from "./webllm-model-registry";

export type BrowserComputeTier = "T0" | "T1" | "T2" | "T3";
export type BrowserComputePolicy =
  | "browser-first"
  | "balanced"
  | "quality-first"
  | "manual";
export type BrowserQualityClass =
  | "deterministic"
  | "semantic"
  | "fast"
  | "balanced"
  | "quality_local_browser"
  | "heavy_private";

export const BROWSER_T0_OPERATIONS = [
  "rpg.success-rate",
  "rpg.stat-boundary",
  "rpg.experience-level",
  "rpg.inventory-ledger",
  "game.progress",
  "candidate.diff",
  "schema.validation",
  "json.repair",
  "format.validation",
  "canon.revision-check",
  "candidate.digest",
  "candidate.deduplicate",
  "candidate.similarity",
  "cache.key",
  "context.token-estimate",
  "content-safety.metadata",
  "structured-output.validation",
  "approval.preview",
  "backup.semantic-hash",
] as const;

export const BROWSER_T1_TASKS = new Set<PlatformTaskType>([
  "story.summary",
  "story.chapterReview",
  "story.consistencyCheck",
  "story.timelineCheck",
  "story.characterCheck",
  "story.worldRuleCheck",
  "story.foreshadowingCheck",
  "story.retrieval",
  "story.plotAnalysis",
  "story.pacingCheck",
  "story.originalityCheck",
  "drama.chapterClassify",
  "drama.sceneClassify",
  "drama.characterPresence",
  "drama.emotionCurve",
  "drama.shortSummary",
  "character.nameExtract",
  "character.traitClassify",
  "character.voiceClassify",
  "character.emotionClassify",
  "character.relationshipEventClassify",
  "character.dialogueConsistency",
  "game.stateEvaluation",
]);

/**
 * These tasks have two truthful Browser implementations. They use the T2
 * generative path only when a measured generative runtime is ready; otherwise
 * they remain T1 semantic/deterministic work instead of pretending that a
 * packaged transform was generated by an LLM.
 */
export const BROWSER_T1_T2_HYBRID_TASKS = new Set<PlatformTaskType>([
  "chapter.compress",
]);

export const BROWSER_T2_TASKS = new Set<PlatformTaskType>([
  "assistant.general",
  "assistant.brainstorm",
  "assistant.critique",
  "assistant.transform",
  "creation.genreSuggestions",
  "creation.titleCandidates",
  "creation.coreIdeaCandidates",
  "creation.protagonistCandidates",
  "creation.worldCandidates",
  "creation.conflictCandidates",
  "creation.storySeed",
  "creation.guidedChoices",
  "chapter.outline",
  "chapter.continue",
  "chapter.rewrite",
  "chapter.expand",
  "chapter.abcChoices",
  "chapter.endingCandidates",
  "story.plotCandidate",
  "story.themeAnalysis",
  "story.endingPlan",
  "knowledge.ruleExtraction",
  "knowledge.ruleSynthesis",
  "learning.preferenceReview",
  "character.create",
  "character.dialogue",
  "character.relationshipAnalysis",
  "character.arcCandidate",
  "character.actionPlan",
  "character.evaluate",
  "character.relationshipImpact",
  "world.create",
  "world.ruleCandidate",
  "world.locationCandidate",
  "world.factionCandidate",
  "game.rewardCandidate",
  "game.questCandidate",
  "game.achievementCandidate",
  "drama.scenePlan",
  "drama.dialogue",
  "drama.branchCandidate",
  "drama.continuity",
  "drama.beatSuggestion",
]);

export const BROWSER_T3_TASKS = new Set<PlatformTaskType>([
  "character.multiAgentSimulation",
  "character.privateArc",
  "story.storyBibleCandidate",
  "drama.episodePlan",
  "drama.ending",
]);

export type BrowserTaskEligibility = {
  taskType: PlatformTaskType;
  tier: BrowserComputeTier;
  eligible: boolean;
  browserExecutor:
    | "deterministic"
    | "semantic-worker"
    | "webllm-worker"
    | "chromium-prompt-api"
    | null;
  qualityClass: BrowserQualityClass;
  reasonCode: string;
  requiresExplicitEscalation: boolean;
  recommendedProvider: PlatformProviderId;
  contextTokens: number;
  outputTokens: number;
  benchmarkRequired: boolean;
  benchmarkPassed: boolean;
  plannedPipeline: string[];
};

function browserModelLimits(parameterLabel: BrowserWebLLMModelManifest["parameterLabel"] | null) {
  if (parameterLabel === "3B") {
    return { context: 2_850, output: 1_024, qualityClass: "quality_local_browser" as const };
  }
  if (parameterLabel === "1.5B") {
    return { context: 2_200, output: 768, qualityClass: "balanced" as const };
  }
  return { context: 1_200, output: 384, qualityClass: "fast" as const };
}

export function classifyBrowserTask(taskType: PlatformTaskType): BrowserComputeTier {
  if (BROWSER_T3_TASKS.has(taskType)) return "T3";
  if (BROWSER_T2_TASKS.has(taskType)) return "T2";
  if (BROWSER_T1_T2_HYBRID_TASKS.has(taskType)) return "T1";
  if (BROWSER_T1_TASKS.has(taskType)) return "T1";
  return "T3";
}

export function resolveBrowserTaskEligibility(input: {
  taskType: PlatformTaskType;
  policy?: BrowserComputePolicy;
  manualProvider?: PlatformProviderId;
  generativeModelReady: boolean;
  generativeRuntime?: "webllm-worker" | "chromium-prompt-api" | null;
  inferenceProofVerified: boolean;
  semanticModelReady?: boolean;
  modelParameterLabel?: BrowserWebLLMModelManifest["parameterLabel"] | null;
  benchmark?: Pick<BrowserDeviceBenchmark, "benchmarkPassed"> | null;
  contextTokens?: number;
  outputTokens?: number;
  qualityPreference?: "fast" | "balanced" | "high";
  allowPreAuthorizedClosedEscalation?: boolean;
}): BrowserTaskEligibility {
  const policy = input.policy ?? "browser-first";
  const tier = BROWSER_T1_T2_HYBRID_TASKS.has(input.taskType)
    && input.generativeModelReady
    && input.inferenceProofVerified
    ? "T2"
    : classifyBrowserTask(input.taskType);
  const contextTokens = Math.max(0, Math.round(input.contextTokens ?? 0));
  const outputTokens = Math.max(0, Math.round(input.outputTokens ?? 384));
  const limits = browserModelLimits(input.modelParameterLabel ?? null);
  const benchmarkPassed = Boolean(input.benchmark?.benchmarkPassed);
  const browserExecutor = input.generativeRuntime ?? "webllm-worker";
  const base = {
    taskType: input.taskType,
    tier,
    contextTokens,
    outputTokens,
    benchmarkRequired: tier === "T2",
    benchmarkPassed,
  };

  if (policy === "manual" && input.manualProvider !== "browser-ai") {
    const recommendedProvider = input.manualProvider ?? "local-ollama";
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: tier === "T3" ? "heavy_private" : limits.qualityClass,
      reasonCode: "MANUAL_PROVIDER_LOCKED",
      requiresExplicitEscalation: false,
      recommendedProvider,
      plannedPipeline: ["user-selected-provider"],
    };
  }

  if (tier === "T1") {
    return {
      ...base,
      eligible: true,
      browserExecutor: input.semanticModelReady === false
        ? "deterministic"
        : "semantic-worker",
      qualityClass: input.semanticModelReady === false
        ? "deterministic"
        : "semantic",
      reasonCode: input.semanticModelReady === false
        ? "BROWSER_T1_DETERMINISTIC_DEGRADED"
        : "BROWSER_T1_SEMANTIC_READY",
      requiresExplicitEscalation: false,
      recommendedProvider: "browser-ai",
      plannedPipeline: ["browser-retrieval", "browser-semantic", "browser-evaluator"],
    };
  }

  if (tier === "T3") {
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: "heavy_private",
      reasonCode: "BROWSER_T3_EXPLICIT_ESCALATION_REQUIRED",
      requiresExplicitEscalation: true,
      recommendedProvider: "private-ai-hub",
      plannedPipeline: ["browser-precompute", "explicit-private-hub-consent"],
    };
  }

  if (policy === "quality-first") {
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: limits.qualityClass,
      reasonCode: "QUALITY_FIRST_BROWSER_PRECOMPUTE_ONLY",
      requiresExplicitEscalation: !input.allowPreAuthorizedClosedEscalation,
      recommendedProvider: "local-ollama",
      plannedPipeline: ["browser-precompute", "local-ollama-generation", "browser-quality-gate"],
    };
  }

  if (!input.generativeModelReady || !input.inferenceProofVerified) {
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: limits.qualityClass,
      reasonCode: !input.generativeModelReady
        ? "BROWSER_GENERATIVE_MODEL_NOT_READY"
        : "BROWSER_INFERENCE_PROOF_NOT_VERIFIED",
      requiresExplicitEscalation: true,
      recommendedProvider: "local-ollama",
      plannedPipeline: ["browser-precompute", "ask-before-local-escalation"],
    };
  }

  if (!benchmarkPassed) {
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: limits.qualityClass,
      reasonCode: "BROWSER_ACTUAL_BENCHMARK_REQUIRED",
      requiresExplicitEscalation: true,
      recommendedProvider: "local-ollama",
      plannedPipeline: ["browser-precompute", "run-device-benchmark"],
    };
  }

  if (contextTokens > limits.context || outputTokens > limits.output) {
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: limits.qualityClass,
      reasonCode: "BROWSER_TASK_EXCEEDS_VERIFIED_BUDGET",
      requiresExplicitEscalation: true,
      recommendedProvider: "local-ollama",
      plannedPipeline: ["browser-context-compression", "ask-before-local-escalation"],
    };
  }

  if (
    input.qualityPreference === "high"
    && input.modelParameterLabel !== "3B"
    && policy !== "browser-first"
  ) {
    return {
      ...base,
      eligible: false,
      browserExecutor: null,
      qualityClass: limits.qualityClass,
      reasonCode: "HIGH_QUALITY_REQUIRES_EXPLICIT_LOCAL_REFINEMENT",
      requiresExplicitEscalation: true,
      recommendedProvider: "local-ollama",
      plannedPipeline: ["browser-draft", "ask-before-local-refinement"],
    };
  }

  return {
    ...base,
    eligible: true,
    browserExecutor,
    qualityClass: limits.qualityClass,
    reasonCode: "BROWSER_T2_VERIFIED_AND_WITHIN_BUDGET",
    requiresExplicitEscalation: false,
    recommendedProvider: "browser-ai",
    plannedPipeline: input.modelParameterLabel === "3B"
      ? ["browser-planner", "browser-draft", "browser-critic", "browser-revision", "browser-evaluator"]
      : ["browser-draft", "browser-deterministic-evaluator"],
  };
}
