"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

type ReaderProject={id:string;title:string;chapterTitle:string;draft:string;updatedAt:string;topicName?:string|null};
type ReaderSettings={theme:"light"|"night"|"eye"|"paper";fontSize:number;lineHeight:number;contentWidth:number;paragraphSpacing:number;animation:boolean};
type ReaderProgress={scrollTop:number;percentage:number;lastReadAt:string;bookmark:boolean;note:string;completed:boolean};
const PROJECT_KEY="novel_p12_studio_state",SETTINGS_KEY="novel_reader_settings",progressKey=(id:string)=>`novel_reader_progress_${id}`;
const defaults:ReaderSettings={theme:"night",fontSize:20,lineHeight:1.9,contentWidth:760,paragraphSpacing:18,animation:true};

export default function ReaderClient({projectId}:{projectId:string}){
  const [project,setProject]=useState<ReaderProject|null>(null),[settings,setSettings]=useState<ReaderSettings>(defaults),[progress,setProgress]=useState<ReaderProgress>({scrollTop:0,percentage:0,lastReadAt:"",bookmark:false,note:"",completed:false}),[directoryOpen,setDirectoryOpen]=useState(false),[loaded,setLoaded]=useState(false);const articleRef=useRef<HTMLElement>(null);
  useEffect(()=>{const timer=setTimeout(()=>{try{const state=JSON.parse(localStorage.getItem(PROJECT_KEY)||"null");setProject(state?.projects?.find((item:ReaderProject)=>item.id===projectId)||null);setSettings({...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"null")});setProgress((current)=>({...current,...JSON.parse(localStorage.getItem(progressKey(projectId))||"null")}))}catch{}setLoaded(true)},0);return()=>clearTimeout(timer)},[projectId]);
  useEffect(()=>{if(!loaded)return;localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))},[settings,loaded]);
  useEffect(()=>{if(!loaded||!progress.scrollTop)return;requestAnimationFrame(()=>window.scrollTo({top:Math.min(progress.scrollTop,document.documentElement.scrollHeight),behavior:settings.animation?"smooth":"auto"}))},[loaded]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!loaded)return;let timer:number;const save=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),percentage=Math.min(100,Math.round(scrollY/max*100));setProgress((current)=>{const next={...current,scrollTop:scrollY,percentage,lastReadAt:new Date().toISOString(),completed:percentage>=95};localStorage.setItem(progressKey(projectId),JSON.stringify(next));return next})},200)};addEventListener("scroll",save,{passive:true});return()=>{removeEventListener("scroll",save);window.clearTimeout(timer)}},[loaded,projectId]);
  const paragraphs=useMemo(()=>(project?.draft||"").split(/\n\s*\n/).map((text)=>text.trim()).filter(Boolean),[project]);
  function saveProgress(partial:Partial<ReaderProgress>){const next={...progress,...partial,lastReadAt:new Date().toISOString()};setProgress(next);localStorage.setItem(progressKey(projectId),JSON.stringify(next))}
  if(!loaded)return <main className="readerEmpty">正在開啟作品……</main>;
  if(!project)return <main className="readerEmpty"><h1>找不到這部作品</h1><p>作品可能保存在另一個瀏覽器或已被移除。</p><Link href="/studio?screen=library">回到我的作品</Link></main>;
  return <main className={`readerShell reader-${settings.theme} ${settings.animation?"":"readerNoMotion"}`} style={{"--reader-size":`${settings.fontSize}px`,"--reader-line":settings.lineHeight,"--reader-width":`${settings.contentWidth}px`,"--reader-space":`${settings.paragraphSpacing}px`} as React.CSSProperties}>
    <header className="readerTop"><Link href="/studio?screen=library">回到作品首頁</Link><span>{progress.percentage}%</span><div><button onClick={()=>setDirectoryOpen(!directoryOpen)}>章節目錄</button><button onClick={()=>saveProgress({bookmark:!progress.bookmark})}>{progress.bookmark?"移除書籤":"加入書籤"}</button></div></header>
    {directoryOpen&&<aside className="readerDirectory"><header><h2>章節目錄</h2><button onClick={()=>setDirectoryOpen(false)}>關閉</button></header><input aria-label="搜尋章名" placeholder="搜尋章名"/><button className="active" onClick={()=>{scrollTo({top:0,behavior:"smooth"});setDirectoryOpen(false)}}><b>第 1 章　{project.chapterTitle}</b><span>{project.draft.length} 字・{progress.completed?"已閱讀":"閱讀中"}{progress.bookmark?"・有書籤":""}</span></button></aside>}
    <section className="readerControls" aria-label="閱讀設定"><label>主題<select value={settings.theme} onChange={(event)=>setSettings({...settings,theme:event.target.value as ReaderSettings["theme"]})}><option value="light">明亮</option><option value="night">深夜</option><option value="eye">護眼</option><option value="paper">羊皮紙</option></select></label><label>字體<input type="range" min="16" max="28" value={settings.fontSize} onChange={(event)=>setSettings({...settings,fontSize:Number(event.target.value)})}/></label><label>行距<input type="range" min="1.5" max="2.4" step=".1" value={settings.lineHeight} onChange={(event)=>setSettings({...settings,lineHeight:Number(event.target.value)})}/></label><label>寬度<input type="range" min="560" max="920" step="20" value={settings.contentWidth} onChange={(event)=>setSettings({...settings,contentWidth:Number(event.target.value)})}/></label><label><input type="checkbox" checked={settings.animation} onChange={(event)=>setSettings({...settings,animation:event.target.checked})}/> 動畫</label></section>
    <article ref={articleRef} className="readerArticle"><header><small>{project.topicName||"作品"}</small><h1>{project.title}</h1><h2>第 1 章　{project.chapterTitle}</h2></header>{paragraphs.length?paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>):<p className="readerNoContent">這一章還沒有正式內容。回到寫作中心開始創作吧。</p>}<footer><button disabled>上一章</button><span>第 1 章／共 1 章</span><button disabled>下一章</button></footer><label className="readerNote">本章私人筆記<textarea value={progress.note} onChange={(event)=>saveProgress({note:event.target.value})} placeholder="筆記只保存在目前瀏覽器，不會交給 AI。"/></label></article>
  </main>
}
