import type { ResearchSourceRecord } from "./types";

const REVIEWED_AT = "2026-08-23";

const STATIC_RIGHTS = {
  basis: "official_facts_and_metadata_only",
  sourceTextCopied: false,
  storyExpressionUsed: false,
  redistributionClaimed: false,
} as const;

const STATIC_ROBOTS = {
  policy: "no_runtime_fetch_static_reference_only",
  checkedForAutomatedCollection: false,
  automatedCollectionPerformed: false,
  robotsOrLoginBypass: false,
} as const;

const NO_CONTENT_RETENTION = {
  rawSourceRetained: false,
  excerptRetained: false,
  transcriptRetained: false,
  postOrVideoBodyRetained: false,
  characterNamesRetained: false,
  dialogueRetained: false,
  reconstructablePlotRetained: false,
} as const;

export const PUBLIC_STORY_RESEARCH_SOURCES_V1 = [
  {
    sourceId: "gutenberg-main-categories",
    url: "https://www.gutenberg.org/ebooks/categories",
    platform: "project_gutenberg",
    sourceType: "official_category_taxonomy",
    sourceFacts: [
      {
        factId: "pg.categories.auto",
        factKind: "official_platform_fact",
        summary: "Project Gutenberg 將主分類說明為類似大型實體書店的瀏覽類別，並標示這些類別為自動指派。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "not_needed",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Project Gutenberg Literary Archive Foundation",
      citationTitle: "Main Categories",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "gutenberg-subject-metadata",
    url: "https://www.gutenberg.org/help/bibliographic_record.html",
    platform: "project_gutenberg",
    sourceType: "official_subject_metadata",
    sourceFacts: [
      {
        factId: "pg.subjects.catalog",
        factKind: "official_platform_fact",
        summary: "Project Gutenberg 的書目紀錄可含一個或多個主題標目，並可用主題連到其他具相同標目的項目。",
      },
      {
        factId: "pg.bookshelves.distinction",
        factKind: "official_platform_fact",
        summary: "Project Gutenberg 區分人工編輯的書架集合與自動產生的瀏覽分類，並提醒書架清單可能已過時。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "not_needed",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Project Gutenberg Literary Archive Foundation",
      citationTitle: "Help on Download Options and Bibliographic Record",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "gutenberg-automation-guidance",
    url: "https://www.gutenberg.org/ebooks/offline_catalogs.html",
    platform: "project_gutenberg",
    sourceType: "official_automation_guidance",
    sourceFacts: [
      {
        factId: "pg.automation.feeds",
        factKind: "official_platform_fact",
        summary: "Project Gutenberg 提供可機器讀取的完整書目元資料，並明確要求開發者使用資料檔而非爬取網站。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "not_needed",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Project Gutenberg Literary Archive Foundation",
      citationTitle: "Offline Catalogs and Feeds",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "royal-road-genres-tags",
    url: "https://www.royalroad.com/support/knowledgebase/98",
    platform: "royal_road",
    sourceType: "official_genre_tag_taxonomy",
    sourceFacts: [
      {
        factId: "rr.genres.broad",
        factKind: "official_platform_fact",
        summary: "Royal Road 的官方說明以類型表示較寬的故事分類。",
      },
      {
        factId: "rr.tags.fine",
        factKind: "official_platform_fact",
        summary: "Royal Road 將標籤定義為比類型更細的主題與情節機制分類，並要求標記符合內容。",
      },
      {
        factId: "rr.tags.discovery",
        factKind: "official_platform_fact",
        summary: "Royal Road 說明讀者可組合類型與標籤進行搜尋，並可在進階搜尋中納入或排除。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "not_needed",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Royal Road",
      citationTitle: "Genres and Tags",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "youtube-recommendation-guidance",
    url: "https://support.google.com/youtube/answer/16533387?hl=en",
    platform: "youtube",
    sourceType: "official_recommendation_guidance",
    sourceFacts: [
      {
        factId: "yt.recommendation.objective",
        factKind: "official_platform_fact",
        summary: "YouTube 說明推薦系統的目標是為每位觀眾找到適合的內容並支持長期滿意度，而非提供單一爆紅公式。",
      },
      {
        factId: "yt.recommendation.signals",
        factKind: "official_platform_fact",
        summary: "YouTube 將推薦訊號概括為觀眾個人化與內容表現，例如是否點選、觀看或正向互動。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "account_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "YouTube Help",
      citationTitle: "YouTube's Recommendation System",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "youtube-retention-guidance",
    url: "https://support.google.com/youtube/answer/9313698?hl=en",
    platform: "youtube",
    sourceType: "official_retention_analytics_guidance",
    sourceFacts: [
      {
        factId: "yt.retention.key_moments",
        factKind: "official_platform_fact",
        summary: "YouTube Analytics 的關鍵留存時刻報告用來觀察影片不同時點留住注意的表現。",
      },
      {
        factId: "yt.retention.comparison",
        factKind: "official_platform_fact",
        summary: "YouTube 提供與近期相似長度內容的典型留存比較；比較是觀測工具，不是故事成功保證。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "account_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "YouTube Help",
      citationTitle: "Understand your YouTube engagement",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "youtube-content-grouping-guidance",
    url: "https://support.google.com/youtube/answer/13616340?hl=en",
    platform: "youtube",
    sourceType: "official_content_grouping_guidance",
    sourceFacts: [
      {
        factId: "yt.grouping.axes",
        factKind: "official_platform_fact",
        summary: "YouTube 建議依格式、系列、風格或語氣、預期受眾、主題壽命與成本預算將內容分組。",
      },
      {
        factId: "yt.grouping.compare",
        factKind: "official_platform_fact",
        summary: "YouTube 建議在共同時間範圍比較群組表現，並檢查單一高峰是否扭曲平均值。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "account_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "YouTube Help",
      citationTitle: "Tips to learn what content to create",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "instagram-insights-metrics",
    url: "https://www.facebook.com/help/instagram/788388387972460",
    platform: "meta_instagram",
    sourceType: "official_public_insights_metric_definition",
    sourceFacts: [
      {
        factId: "ig.insights.metrics",
        factKind: "official_platform_fact",
        summary: "Instagram Insights 將內容表現指標列為觀看次數、觸及帳號、互動與參與帳號等項目。",
      },
      {
        factId: "ig.insights.metric_scope",
        factKind: "official_platform_fact",
        summary: "Instagram 區分顯示或播放次數與至少看過一次的不重複帳號，並說明部分指標為估計值。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "account_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Instagram Help Center / Meta",
      citationTitle: "About Instagram Insights",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "facebook-dashboard-insights",
    url: "https://www.facebook.com/help/3714470172128723",
    platform: "meta_facebook",
    sourceType: "official_public_insights_metric_definition",
    sourceFacts: [
      {
        factId: "fb.insights.aggregate",
        factKind: "official_platform_fact",
        summary: "Facebook Dashboard 以彙總資料顯示內容互動情形，涵蓋貼文、Reels 與影片。",
      },
      {
        factId: "fb.insights.metrics",
        factKind: "official_platform_fact",
        summary: "Facebook 列舉的彙總指標包含觀看、播放、重播、反應、留言與分享等活動。",
      },
    ],
    rights: STATIC_RIGHTS,
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "account_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Facebook Help Center / Meta",
      citationTitle: "About Dashboard",
      authors: [],
      publishedYear: null,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "trabasso-van-den-broek-1985",
    url: "https://doi.org/10.1016/0749-596X(85)90049-X",
    platform: "peer_reviewed_research",
    sourceType: "peer_reviewed_original_research",
    sourceFacts: [
      {
        factId: "study.causal_network.method",
        factKind: "study_method",
        summary: "該研究以故事事件的因果網路表示，分析即時與延遲回憶、摘要及事件重要性判斷。",
      },
      {
        factId: "study.causal_network.result",
        factKind: "study_result",
        summary: "研究報告指出，事件是否位於因果鏈及其因果連結數，可解釋多項記憶與重要性測量的獨特變異。",
      },
    ],
    rights: {
      basis: "scholarly_metadata_and_abstract_summary_only",
      sourceTextCopied: false,
      storyExpressionUsed: false,
      redistributionClaimed: false,
    },
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_abstract_only",
      metricOrFullTextAccess: "subscription_or_library_may_be_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Journal of Memory and Language / Elsevier",
      citationTitle: "Causal thinking and the representation of narrative events",
      authors: ["Tom Trabasso", "Paul van den Broek"],
      publishedYear: 1985,
      doi: "10.1016/0749-596X(85)90049-X",
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "bezdek-et-al-2015",
    url: "https://pubmed.ncbi.nlm.nih.gov/26143014/",
    platform: "peer_reviewed_research",
    sourceType: "peer_reviewed_original_research",
    sourceFacts: [
      {
        factId: "study.suspense_attention.method",
        factKind: "study_method",
        summary: "該原始研究使用 fMRI，檢驗視聽敘事中懸念上升時中央與周邊視覺刺激的處理變化。",
      },
      {
        factId: "study.suspense_attention.result",
        factKind: "study_result",
        summary: "研究報告指出，懸念上升時周邊視覺處理活動降低，與中央及注意相關處理的活動增加。",
      },
    ],
    rights: {
      basis: "scholarly_metadata_and_abstract_summary_only",
      sourceTextCopied: false,
      storyExpressionUsed: false,
      redistributionClaimed: false,
    },
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_abstract_only",
      metricOrFullTextAccess: "subscription_or_library_may_be_required",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Neuroscience / PubMed",
      citationTitle: "Neural evidence that suspense narrows attentional focus",
      authors: ["Michael A. Bezdek", "Richard J. Gerrig", "W. G. Wenzel", "Joon Shin", "Kaitlin Pirog Revill", "Eric H. Schumacher"],
      publishedYear: 2015,
      doi: "10.1016/j.neuroscience.2015.06.055",
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "lehne-et-al-2015",
    url: "https://doi.org/10.1371/journal.pone.0124550",
    platform: "peer_reviewed_research",
    sourceType: "peer_reviewed_original_research",
    sourceFacts: [
      {
        factId: "study.suspense_reading.method",
        factKind: "study_method",
        summary: "該開放取用原始研究在參與者首次閱讀分段懸念文學時收集 fMRI，並請其逐段評分主觀懸念。",
      },
      {
        factId: "study.suspense_reading.result",
        factKind: "study_result",
        summary: "研究報告指出，主觀懸念與心智推測、預測推論及可能的認知控制相關腦區活動有關。",
      },
    ],
    rights: {
      basis: "open_access_research_facts_only",
      sourceTextCopied: false,
      storyExpressionUsed: false,
      redistributionClaimed: false,
    },
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "public_without_login",
      metricOrFullTextAccess: "not_needed",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "PLOS ONE",
      citationTitle: "Reading a Suspenseful Literary Text Activates Brain Areas Related to Social Cognition and Predictive Inference",
      authors: ["Moritz Lehne", "Philipp Engel", "Martin Rohrmeier", "Winfried Menninghaus", "Arthur M. Jacobs", "Stefan Koelsch"],
      publishedYear: 2015,
      doi: "10.1371/journal.pone.0124550",
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
  {
    sourceId: "novel-anti-despair-policy-v1",
    url: "urn:novel:product-policy:anti-despair:v1",
    platform: "novel_product_policy",
    sourceType: "local_product_safety_policy",
    sourceFacts: [
      {
        factId: "policy.anti_despair.required",
        factKind: "product_requirement",
        summary: "產品要求分支保留可負擔的復原或穩態路徑、失敗推進、代價預告、連續挫敗緩衝與三選項差異化後果。",
      },
    ],
    rights: {
      basis: "owned_product_policy",
      sourceTextCopied: false,
      storyExpressionUsed: false,
      redistributionClaimed: false,
    },
    robots: STATIC_ROBOTS,
    publicAccess: {
      sourcePage: "local_builtin",
      metricOrFullTextAccess: "not_needed",
      observedAt: REVIEWED_AT,
    },
    provenance: {
      publisher: "Novel local product policy",
      citationTitle: "Anti-despair causal choice policy v1",
      authors: [],
      publishedYear: 2026,
      doi: null,
      reviewedAt: REVIEWED_AT,
      manuallySummarized: true,
    },
    retention: NO_CONTENT_RETENTION,
  },
] as const satisfies readonly ResearchSourceRecord[];
