import type { CapabilityStatus } from "./capability-status";

export type CapabilityDefinition = {
  id: string;
  contractStatus: CapabilityStatus;
  runtimeStatus: CapabilityStatus;
  evidence: string[];
  limitations?: string[];
};

export const CAPABILITY_REGISTRY: CapabilityDefinition[] = [
  { id: "indexedDb.core", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["IndexedDbNovelRepository schema v6"] },
  { id: "indexedDb.projects", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["projects store and projectId index"] },
  { id: "indexedDb.reader", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["readerStates, readerNotes, readerBookmarks stores"] },
  { id: "indexedDb.backups", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["novel-backup-v5 repository export/import"] },
  { id: "indexedDb.acceptedChoices", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["acceptedChoices store, schema v4"] },
  { id: "indexedDb.storyBranches", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["storyBranches store, schema v4"] },
  { id: "indexedDb.fullAdoption", contractStatus: "partial", runtimeStatus: "partial", evidence: ["Studio canonical interaction data uses IndexedDB"], limitations: ["Legacy compatibility metadata remains in localStorage"] },
  { id: "backup.repository", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["NovelRepository exportProject/importProject"] },
  { id: "backup.create", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["createProjectBackup"] },
  { id: "backup.export", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["novel-backup-v5 manifest and SHA-256"] },
  { id: "backup.importCopy", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["recursive ID remap"] },
  { id: "backup.restoreReplace", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["single IndexedDB replace transaction"] },
  { id: "backup.hashValidation", contractStatus: "ready", runtimeStatus: "ready", evidence: ["SHA-256 contentHash validation"] },
  { id: "backup.safeRestorePoint", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["backups store excluded from replace deletion"] },
  { id: "backup.acceptedChoices", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["acceptedChoices included in NOVEL_STORES"] },
  { id: "backup.storyBranches", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["storyBranches included in NOVEL_STORES"] },
  { id: "repository.approvalTransaction", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["IndexedDB v4 atomic acceptance transaction"] },
  { id: "repository.revisionGuard", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["project, chapter, candidate, story state, Story Bible revision guards"] },
  { id: "repository.idempotency", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["payload-bound idempotencyRecords store"] },
  { id: "backup.approvalTransactions", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["approvalTransactions included in backup manifest"] },
  { id: "backup.idempotencyRecords", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["idempotencyRecords included in backup manifest"] },
  { id: "browser.permissionGateway", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["R1K automated browser permission matrix"], limitations: ["Permission verification does not imply Browser AI runtime availability"] },
  { id: "browser.aiRuntime", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Chrome Summarizer capability probe and fixed-input inference proof"], limitations: ["Availability and model download state depend on each client device"] },
  { id: "ollama.localRuntime", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Paired loopback bridge, model inference proof and streaming provider adapter"], limitations: ["Availability and installed models depend on each client device"] },
  { id: "dramaOsCore", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["drama-os-v1 project, episode, scene and evaluation contracts"] },
  { id: "novelToDramaProjection", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["projectNovelToDrama source-grounded candidate pipeline"] },
  { id: "episodePlanner", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Format-aware episode planner"] },
  { id: "scenePlanner", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Beat-linked scene planner"] },
  { id: "beatSheet", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Profile-constrained beat sheet"] },
  { id: "hookEngine", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Opening hook and cliffhanger engines"] },
  { id: "emotionCurve", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Event-linked emotion curve"] },
  { id: "interactiveDramaCandidates", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Distinct A/B/C creator candidates; canonicalMutation=0"] },
  { id: "dramaApproval", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Atomic Drama Adaptation approval transaction with revision and idempotency guards"] },
  { id: "dramaBackup", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["novel-backup-v5 includes Drama OS and Character Agent stores and accepts v3/v4"] },
  { id: "creationDna", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: ["Reference contract only"], limitations: ["No Creation DNA repository or UI"] },
  { id: "storyBlueprintWorkbench", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: ["Reference contract only"], limitations: ["No Blueprint workbench or authoritative repository"] },
  { id: "worldWorkbench", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: ["Reference contract only"], limitations: ["No world workbench"] },
  { id: "characterWorkbench", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: ["Reference and knowledge-scope contracts only"], limitations: ["No character workbench or relationship graph"] },
  { id: "aiBookDiscovery", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled outside P2.4A"] },
  { id: "authorAnalytics", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled outside P2.4A"] },
  { id: "translationWorkbench", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled outside P2.4A"] },
  { id: "coverDirection", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled outside P2.4A"] },
  { id: "rpgMode", contractStatus: "partial", runtimeStatus: "partial", evidence: ["Legacy consumer mode metadata and stat presentation"], limitations: ["No unified P2.5 canonical workbench"] },
  { id: "cultivationMode", contractStatus: "partial", runtimeStatus: "partial", evidence: ["Legacy genre and theme support"], limitations: ["No dedicated cultivation progression engine"] },
  { id: "managementMode", contractStatus: "partial", runtimeStatus: "partial", evidence: ["Legacy consumer mode metadata and stat presentation"], limitations: ["No unified P2.5 canonical workbench"] },
  { id: "characterAgentCore", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["character-agent-v1 scoped agent loop and deterministic evaluator"] },
  { id: "characterPerspectiveContext", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["physically separated CharacterActorContext and CharacterEvaluatorContext"] },
  { id: "knowledgeScopedCharacterContext", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Knowledge Scope Gateway with tainted deny trace"] },
  { id: "characterBeliefEngine", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["belief and false-belief candidates isolated from Canonical Truth"] },
  { id: "characterMemory", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["per-character temporal memory retrieval and promotion gate"] },
  { id: "relationshipGraph", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["directed relationship graph with bounded metrics"] },
  { id: "relationshipHistory", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["source-bound idempotent relationship events"] },
  { id: "privateCharacterSimulation", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["private arc and isolated simulation with canonicalMutation=0"] },
  { id: "multiCharacterSimulation", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["fair turn scheduler, replay structure and termination guards"] },
  { id: "characterProposalApproval", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["shared Proposal Envelope and atomic approval transaction"] },
  { id: "audienceVoting", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled for P2.4D"] },
  { id: "audienceLearning", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled for P2.4D"] },
  { id: "visualCharacterBible", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled for P2.4C"] },
  { id: "storyboard", contractStatus: "not_implemented", runtimeStatus: "not_implemented", evidence: [], limitations: ["Scheduled for P2.4C"] },
  { id: "realVideoGeneration", contractStatus: "contract_only", runtimeStatus: "not_connected", evidence: ["Generic media provider contract only"], limitations: ["Scheduled for P2.4E"] },
  { id: "privateAiHub", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Self-hosted loopback private node, independent pairing, work queue and real model transport"], limitations: ["No remote cloud private hub is claimed; the local private node must be running and paired"] },
  { id: "offlinePreferenceTraining", contractStatus: "ready", runtimeStatus: "client_dependent", evidence: ["Pairwise logistic trainer, immutable artifact, activation and rollback"], limitations: ["Trains a style preference adapter, not LLM weights"] },
  { id: "modelTraining", contractStatus: "not_started", runtimeStatus: "not_started", evidence: ["P2.4A architecture roadmap entry"], limitations: ["No product implementation, training run, model artifact, or callable runtime exists"] },
  { id: "distillation", contractStatus: "not_started", runtimeStatus: "not_started", evidence: ["P2.4A architecture roadmap entry"], limitations: ["No product implementation, distillation run, model artifact, or callable runtime exists"] },
  { id: "media.storyboard", contractStatus: "contract_only", runtimeStatus: "not_connected", evidence: ["story-media-extension-v1 source-bound candidate contract"], limitations: ["No media generation runtime is connected"] },
  { id: "media.videoPrompt", contractStatus: "contract_only", runtimeStatus: "not_connected", evidence: ["story-media-extension-v1 prompt package"], limitations: ["Output remains an approval candidate"] },
  { id: "media.videoGeneration", contractStatus: "contract_only", runtimeStatus: "not_connected", evidence: ["generic video provider adapter contract"], limitations: ["No Seedance or other video provider is installed or authorized"] },
  { id: "backup.legacyFormatImport", contractStatus: "partial", runtimeStatus: "partial", evidence: ["Legacy project migration preview"], limitations: ["Ambiguous legacy interactions require manual review"] },
];
