import type { VideoProviderCapabilities, VideoProviderDescriptor } from "./video-production";

const BASE_CAPABILITIES: VideoProviderCapabilities = {
  textToVideo: true,
  imageReferences: false,
  videoReferences: false,
  audioReferences: false,
  synchronizedAudio: false,
  videoExtension: false,
  timestampEditing: false,
  maxClipSeconds: null,
  maxImageReferences: null,
  maxVideoReferences: null,
  maxAudioReferences: null,
  aspectRatios: ["16:9", "9:16", "1:1"],
  resolutions: ["720p"],
};

export const VIDEO_PROVIDER_REGISTRY: readonly VideoProviderDescriptor[] = [
  {
    providerId: "seedance-2.5-official",
    displayName: "BytePlus Seedance 2.5（官方 LAS API）",
    connectionKind: "official_api",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: {
      ...BASE_CAPABILITIES,
      imageReferences: true,
      videoReferences: true,
      audioReferences: true,
      synchronizedAudio: true,
      videoExtension: true,
      timestampEditing: true,
      maxClipSeconds: 30,
      maxImageReferences: 30,
      maxVideoReferences: 10,
      maxAudioReferences: 10,
      aspectRatios: ["adaptive", "16:9", "9:16", "1:1"],
      resolutions: ["480p", "720p"],
    },
    publicProductUrl: "https://www.byteplus.com/en/product/modelark",
    publicApiUrl: "https://docs.byteplus.com/en/docs/byteplus_las/video_gen_enhanced",
    availabilityNote: "官方 Seedance 2.5 建立／查詢契約與伺服器轉接器已完成測試；目前缺伺服器憑證、使用者隔離的永久工作儲存與私有 MP4 驗證儲存，因此仍不會付費送件。",
    contractStatus: "implemented_tested",
    lifecycle: "active",
    shutdownAt: null,
    remoteCancel: "supported",
    outputUrlTtlHours: 24,
    setupChecklist: ["設定伺服器端憑證", "部署使用者隔離的永久工作佇列", "部署私有成品隔離區與 MP4 驗證", "設定費用上限及素材權利憑證"],
  },
  {
    providerId: "byteplus-las-preview-contract",
    displayName: "BytePlus 舊版試驗契約",
    connectionKind: "official_api",
    availability: "disabled",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: {
      ...BASE_CAPABILITIES,
      synchronizedAudio: true,
      maxClipSeconds: 30,
      aspectRatios: ["adaptive", "16:9", "9:16", "1:1"],
      resolutions: ["480p", "720p"],
    },
    publicProductUrl: null,
    publicApiUrl: null,
    availabilityNote: "保留作為伺服器契約測試，不視為 Seedance 2.5 官方連接，正式環境禁止送件。",
    contractStatus: "deprecated",
    lifecycle: "deprecated",
    shutdownAt: null,
    remoteCancel: "unknown",
  },
  {
    providerId: "runway-official",
    displayName: "Runway（官方 API）",
    connectionKind: "official_api",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true, videoReferences: true, videoExtension: true },
    publicProductUrl: "https://runwayml.com/",
    publicApiUrl: "https://docs.dev.runwayml.com/api/",
    availabilityNote: "官方 API 有建立、查詢與取消工作；Novel 尚未安裝轉接器、憑證、費用上限、永久工作儲存與成品驗證。",
    contractStatus: "catalog_only",
    lifecycle: "active",
    shutdownAt: null,
    remoteCancel: "supported",
    outputUrlTtlHours: 24,
    setupChecklist: ["實作並沙箱驗證官方轉接器", "設定伺服器端憑證", "部署永久工作與成品驗證儲存", "設定費用與重試上限"],
  },
  {
    providerId: "openai-sora-official",
    displayName: "Sora（官方 API）",
    connectionKind: "official_api",
    availability: "disabled",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true },
    publicProductUrl: "https://openai.com/sora/",
    publicApiUrl: "https://developers.openai.com/api/reference/resources/videos",
    availabilityNote: "官方 Videos API 已標示 Deprecated，並預定於 2026-09-24 永久關閉；Novel 不新增此轉接器，也不接受新工作。",
    contractStatus: "deprecated",
    lifecycle: "deprecated",
    shutdownAt: "2026-09-24",
    remoteCancel: "unsupported",
    outputUrlTtlHours: null,
    setupChecklist: ["不要建立新整合", "既有使用者應遷移至仍受支援的供應商"],
  },
  {
    providerId: "google-veo-official",
    displayName: "Veo（官方 API）",
    connectionKind: "official_api",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true, synchronizedAudio: true },
    publicProductUrl: "https://deepmind.google/models/veo/",
    publicApiUrl: "https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/veo-video-generation",
    availabilityNote: "應以明確的 Veo 3.1 版本建立長工作轉接器；目前缺 GCP 專案、區域、服務帳號、永久工作儲存與成品驗證。",
    contractStatus: "catalog_only",
    lifecycle: "active",
    shutdownAt: null,
    remoteCancel: "unknown",
    outputUrlTtlHours: null,
    setupChecklist: ["選定 Veo 3.1 版本與區域", "設定伺服器端服務帳號", "實作長工作輪詢", "部署永久工作與成品驗證儲存"],
  },
  {
    providerId: "local-video-worker",
    displayName: "自架 GPU 影片工作站",
    connectionKind: "self_hosted_worker",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: false,
    requiresExternalConsent: false,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true, videoReferences: true, synchronizedAudio: true },
    publicProductUrl: null,
    publicApiUrl: null,
    availabilityNote: "Novel Video Engine worker 契約已內建；需要在自己的 GPU 主機部署 allowlisted 模型（如 Wan2.2 或經授權的 LTX）、佇列與私有成品驗證後才會執行。這不是重造 Seedance 基礎模型。",
    contractStatus: "implemented_tested",
    lifecycle: "active",
    shutdownAt: null,
    remoteCancel: "supported",
    outputUrlTtlHours: null,
    setupChecklist: ["部署 HTTPS worker wrapper", "鎖定模型權重與 workflow 雜湊", "設定伺服器端 token", "部署永久工作與私有 MP4 驗證"],
  },
];

export function listVideoProviders() {
  return VIDEO_PROVIDER_REGISTRY.map((provider) => ({
    ...provider,
    setupChecklist: provider.setupChecklist ? [...provider.setupChecklist] : undefined,
    capabilities: {
      ...provider.capabilities,
      aspectRatios: [...provider.capabilities.aspectRatios],
      resolutions: [...provider.capabilities.resolutions],
    },
  }));
}

export function getVideoProvider(providerId: string | null | undefined) {
  const provider = VIDEO_PROVIDER_REGISTRY.find((item) => item.providerId === providerId);
  return provider ? listVideoProviders().find((item) => item.providerId === provider.providerId) ?? null : null;
}
