import type { VideoProviderCapabilities, VideoProviderDescriptor } from "./video-production";

const BASE_CAPABILITIES: VideoProviderCapabilities = {
  textToVideo: true,
  imageReferences: false,
  videoReferences: false,
  audioReferences: false,
  synchronizedAudio: false,
  videoExtension: false,
  timestampEditing: false,
  maxClipSeconds: null,
  maxImageReferences: null,
  maxVideoReferences: null,
  maxAudioReferences: null,
  aspectRatios: ["16:9", "9:16", "1:1"],
  resolutions: ["720p"],
};

export const VIDEO_PROVIDER_REGISTRY: readonly VideoProviderDescriptor[] = [
  {
    providerId: "seedance-2.5-official",
    displayName: "Seedance 2.5（官方 API）",
    connectionKind: "official_api",
    availability: "requires_vendor_onboarding",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: {
      ...BASE_CAPABILITIES,
      imageReferences: true,
      videoReferences: true,
      audioReferences: true,
      synchronizedAudio: true,
      videoExtension: true,
      timestampEditing: true,
      maxClipSeconds: 30,
      maxImageReferences: 30,
      maxVideoReferences: 10,
      maxAudioReferences: 10,
      aspectRatios: ["adaptive", "16:9", "9:16", "1:1"],
      resolutions: ["720p"],
    },
    publicProductUrl: "https://seed.bytedance.com/en/seedance2_5",
    publicApiUrl: null,
    availabilityNote: "官方產品頁已提供 Get API 入口；本專案仍須取得可核驗的模型識別、端點、憑證與條款並完成伺服器轉接，之前不會送件。",
  },
  {
    providerId: "byteplus-las-preview-contract",
    displayName: "BytePlus 舊版試驗契約",
    connectionKind: "official_api",
    availability: "disabled",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: {
      ...BASE_CAPABILITIES,
      synchronizedAudio: true,
      maxClipSeconds: 30,
      aspectRatios: ["adaptive", "16:9", "9:16", "1:1"],
      resolutions: ["480p", "720p"],
    },
    publicProductUrl: null,
    publicApiUrl: null,
    availabilityNote: "保留作為伺服器契約測試，不視為 Seedance 2.5 官方連接，正式環境禁止送件。",
  },
  {
    providerId: "runway-official",
    displayName: "Runway（官方 API）",
    connectionKind: "official_api",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true, videoExtension: true },
    publicProductUrl: "https://runwayml.com/",
    publicApiUrl: null,
    availabilityNote: "尚未安裝官方轉接器，也沒有伺服器端憑證與工作儲存。",
  },
  {
    providerId: "openai-sora-official",
    displayName: "Sora（官方 API）",
    connectionKind: "official_api",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true },
    publicProductUrl: "https://openai.com/sora/",
    publicApiUrl: null,
    availabilityNote: "目前沒有可供本系統送件的已授權影片 API 轉接器。",
  },
  {
    providerId: "google-veo-official",
    displayName: "Veo（官方 API）",
    connectionKind: "official_api",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: true,
    requiresExternalConsent: true,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true, synchronizedAudio: true },
    publicProductUrl: "https://deepmind.google/models/veo/",
    publicApiUrl: null,
    availabilityNote: "尚未安裝官方轉接器，也沒有伺服器端憑證與工作儲存。",
  },
  {
    providerId: "local-video-worker",
    displayName: "自架 GPU 影片工作站",
    connectionKind: "self_hosted_worker",
    availability: "not_configured",
    executionReady: false,
    dataLeavesDevice: false,
    requiresExternalConsent: false,
    supportsAdultNamespace: false,
    capabilities: { ...BASE_CAPABILITIES, imageReferences: true },
    publicProductUrl: null,
    publicApiUrl: null,
    availabilityNote: "需要另行部署 GPU worker、模型權重、佇列、私有成品儲存與 MP4 驗證。",
  },
];

export function listVideoProviders() {
  return VIDEO_PROVIDER_REGISTRY.map((provider) => ({
    ...provider,
    capabilities: {
      ...provider.capabilities,
      aspectRatios: [...provider.capabilities.aspectRatios],
      resolutions: [...provider.capabilities.resolutions],
    },
  }));
}

export function getVideoProvider(providerId: string | null | undefined) {
  const provider = VIDEO_PROVIDER_REGISTRY.find((item) => item.providerId === providerId);
  return provider ? listVideoProviders().find((item) => item.providerId === provider.providerId) ?? null : null;
}
