export const ERROR_CATALOG = {
  STORAGE_UNAVAILABLE: ["儲存空間目前無法使用。", true, false, false, 503],
  STORAGE_QUOTA_EXCEEDED: ["儲存空間不足。請先匯出備份或清理可安全移除的快取。", false, false, true, 507],
  STORAGE_TRANSACTION_FAILED: ["這次儲存沒有完成，原有資料仍然安全。", true, true, true, 500],
  SCHEMA_UNSUPPORTED: ["這份資料來自較新的版本，請使用較新版本的創作中心開啟。", false, true, true, 409],
  MIGRATION_FAILED: ["舊資料轉換沒有完成，原始資料沒有被刪除。", true, true, true, 500],
  MIGRATION_INTERRUPTED: ["資料轉換中斷，可以重新嘗試或先匯出備份。", true, true, true, 409],
  BACKUP_INVALID: ["這不是可用的作品備份檔。", false, false, false, 400],
  BACKUP_HASH_MISMATCH: ["備份檔可能已損壞或被修改，沒有進行匯入。", false, false, false, 400],
  BACKUP_RESTORE_FAILED: ["還原沒有完成，已保留還原前的安全備份。", true, true, true, 500],
  IMPORT_CONFLICT: ["匯入資料與目前作品衝突，請改用建立副本。", false, false, true, 409],
  IMPORT_TOO_LARGE: ["匯入檔案太大，請分割後再試。", false, false, false, 413],
  PROJECT_REVISION_CONFLICT: ["這份內容已在另一個頁面更新，請重新載入後選擇要保留的版本。", true, false, true, 409],
  CANDIDATE_STALE: ["這份建議已不符合最新故事內容，請重新產生。", false, false, false, 409],
  CANDIDATE_ALREADY_ACCEPTED: ["這份建議已經採用，不會重複套用。", false, false, false, 409],
  STORY_EFFECT_INVALID: ["建議的故事影響無法安全套用。", false, false, false, 422],
  STORY_EFFECT_ALREADY_APPLIED: ["這項故事影響已經套用，不會重複計算。", false, false, false, 409],
  AI_PROVIDER_UNAVAILABLE: ["目前選擇的 AI 無法使用，可以改用本機故事規則。", true, false, false, 503],
  AI_PROVIDER_TIMEOUT: ["AI 回應逾時，可以重新嘗試。", true, false, false, 504],
  AI_PROVIDER_CANCELLED: ["AI 任務已取消，作品內容沒有被修改。", false, false, false, 499],
  AI_OUTPUT_INVALID: ["AI 回傳的內容無法安全使用，作品沒有被修改。", true, false, false, 422],
  AI_PRIVACY_POLICY_BLOCKED: ["目前的隱私設定不允許這項 AI 連線。", false, false, false, 403],
  PRIVATE_HUB_UNAUTHORIZED: ["私有 AI 中樞沒有授權。", false, false, false, 401],
  PRIVATE_HUB_QUOTA_EXCEEDED: ["私有 AI 中樞額度不足。", true, false, false, 429],
  READER_POSITION_INVALID: ["上次閱讀位置無法精確定位，已回到最接近的位置。", false, false, false, 200],
  PROJECT_CORRUPTED: ["作品資料無法完整讀取，請先匯出可用備份並查看技術詳細資料。", false, true, true, 422],
} as const;
export type ErrorCode = keyof typeof ERROR_CATALOG;
export function errorInfo(code: ErrorCode) { const [userMessage, retryable, needsRecovery, needsBackup, httpStatus] = ERROR_CATALOG[code]; return { code, userMessage, technicalMessage: code, retryable, needsRecovery, needsBackup, httpStatus, safeToLog: true }; }
