import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
const evidence = JSON.parse(await readFile(path.resolve(process.argv[2]), "utf8"));
assert.equal(evidence.schemaVersion, "r1k-browser-deny-final-evidence-v3");
assert.match(evidence.verdict, /^R1K_(CHROME|EDGE)_DENY_AUTOMATED_PASS$/);
assert.equal(evidence.technical_status, "AUTOMATED_PASS");
assert.equal(evidence.human_validation_status, "HUMAN_NOT_RUN");
assert.equal(evidence.decision_method, "WINDOWS_UI_AUTOMATION");
assert.equal(evidence.human_operator_clicked, false);
assert.equal(evidence.native_prompt.automation_role, "Button");
assert.ok(Number.isInteger(evidence.native_prompt.browser_pid));
assert.equal(evidence.native_prompt.fixed_screen_coordinates_used, false);
assert.equal(evidence.permission.before, "ASK_OR_UNSET");
assert.equal(evidence.permission.after, "DENIED");
assert.equal(evidence.product_error.code, "LOCAL_NETWORK_PERMISSION_DENIED");
assert.equal(evidence.product_error.harness_injected, false);
assert.equal(evidence.network.bridge_browser_requests_received, 0);
assert.equal(evidence.network.external_ai_calls, 0);
assert.equal(evidence.repository.formal_mutation_count, 0);
assert.equal(evidence.counts.FAIL, 0);
assert.equal(evidence.counts.SKIP, 0);
console.log(JSON.stringify({ suite: "r1k-automated-deny-evidence-contract", pass: 17, fail: 0, skip: 0, status: "PASS" }));
