import { NextResponse } from "next/server";
import { pingModel, providerMeta } from "@/lib/novel-ai/provider";
import { aiRunStats, trainingStats } from "@/lib/novel-ai/store";
import { dbAiRunStats, dbTrainingStats, persistenceHealth, runWriteProbe } from "@/lib/novel-ai/persistence";
import { storyBibleHealth } from "@/lib/novel-ai/story-bible";
import { getStorageCapabilities } from "@/lib/novel-ai/storage/registry";

export const runtime = "nodejs";

const RELEASE_META = {
  appCommit: process.env.VERCEL_GIT_COMMIT_SHA || "local-h2p4-universal-local-stage-generation",
  buildTimestamp: process.env.BUILD_TIMESTAMP || "2026-07-16T21:45:00Z",
  releaseTag: "novel-ai-h2p4-universal-local-stage-generation",
};

const L0A2E2D_TEST_META = {
  fullRegressionPassCount: 189,
  fullRegressionFailCount: 0,
  fullRegressionSkipCount: 0,
  parityPassCount: 24,
  parityFailCount: 0,
  paritySkipCount: 0,
  performancePassCount: 19,
  performanceFailCount: 0,
  performanceSkipCount: 0,
  hashParityStatus: "ready",
  dataParityStatus: "ready",
  adapterPerformanceStatus: "baseline_ready",
  extractionP50: 0.55,
  extractionP95: 17.2,
  peakRssMb: 68.11,
  atomicExtractionRoundTrips: 1,
  lastFullAdoptionTestAt: "2026-07-15T06:00:00Z",
  lastFullAdoptionCommit: process.env.VERCEL_GIT_COMMIT_SHA || "local-l0a2e2d",
};

function deploymentId() {
  return process.env.VERCEL_DEPLOYMENT_ID
    || process.env.VERCEL_URL
    || process.env.NEXT_PUBLIC_VERCEL_URL
    || "local";
}

export async function GET() {
  const started = Date.now();
  const meta = providerMeta();
  const memoryRuns = aiRunStats();
  const memoryStats = trainingStats();
  const storyBible = await storyBibleHealth();
  const persistenceBeforeProbe = await persistenceHealth();
  if (persistenceBeforeProbe.persistenceStatus === "ok") await runWriteProbe();
  const persistence = await persistenceHealth();
  let runs: Record<string, unknown> = memoryRuns;
  let stats: Record<string, unknown> = memoryStats;
  const versions = memoryStats.versions;
  if (persistence.persistenceStatus === "ok") {
    try {
      runs = { ...memoryRuns, ...(await dbAiRunStats()) };
      stats = { ...memoryStats, ...(await dbTrainingStats(memoryStats.versions)) };
    } catch {
      runs = memoryRuns;
      stats = memoryStats;
    }
  }
  const configured = meta.configured;
  const ping = configured ? await pingModel() : { ok: false, elapsedMs: 0, error: "MODEL_NOT_CONFIGURED" };
  const writeTest = persistence.writeTestStatus && typeof persistence.writeTestStatus === "object"
    ? {
        status: persistence.writeTestStatus.status,
        lastRunAt: persistence.writeTestStatus.lastRunAt,
        latencyMs: persistence.writeTestStatus.latencyMs,
        cleanupStatus: persistence.writeTestStatus.cleanupStatus,
        errorCode: persistence.writeTestStatus.errorCode,
      }
    : persistence.writeTestStatus;

  return NextResponse.json({
    ...RELEASE_META,
    deploymentId: deploymentId(),
    status: configured ? "ok" : "needs_configuration",
    apiStatus: "online",
    modelStatus: configured ? (ping.ok ? "available" : "configured_but_unavailable") : "not_configured",
    analysisStatus: ping.ok ? "model_ping_success" : runs.lastAnalysisSuccessAt ? "recent_success" : runs.lastError ? "recent_error" : "not_tested",
    provider: meta.provider,
    model: meta.model,
    modelId: meta.modelId,
    modelVersion: meta.modelVersion,
    analyzerVersion: versions.storyAnalyzerVersion,
    benchmarkVersion: versions.candidateAnalyzerVersion,
    databaseProvider: "supabase-postgres",
    database: persistence.storeType,
    storeType: persistence.storeType,
    persistenceStatus: persistence.persistenceStatus,
    databaseStatus: persistence.databaseStatus,
    databaseLatencyMs: persistence.databaseLatencyMs,
    migrationVersion: [persistence.migrationVersion, storyBible.storyBibleMigrationVersion].filter(Boolean).join(","),
    writeTestStatus: writeTest,
    lastSuccessfulWriteAt: persistence.lastSuccessfulWriteAt,
    lastDatabaseError: persistence.lastDatabaseError ? "database_error_available_in_admin_logs" : null,
    dualWriteStatus: persistence.dualWriteStatus,
    key: "server-only",
    fallbackEnabled: true,
    fallbackModel: "local-rule",
    responseTimeMs: Date.now() - started,
    modelPingMs: ping.elapsedMs,
    averageResponseTimeMs: runs.averageLatencyMs,
    lastSuccessAt: runs.lastSuccessAt,
    lastAnalysisSuccessAt: runs.lastAnalysisSuccessAt,
    lastError: ping.ok ? runs.lastError : { createdAt: new Date().toISOString(), taskType: "health", errorCode: ping.error || "MODEL_HEALTH_FAILED" },
    last24hSuccessRate: runs.last24hSuccessRate ?? null,
    last24hFailureRate: runs.last24hFailureRate ?? null,
    dailyTokenUsage: runs.dailyTokens ?? null,
    monthlyEstimatedCost: runs.monthlyEstimatedCost ?? null,
    trainingExamples: stats.trainingExamples,
    feedback: stats.feedback,
    settings: meta.settings,
    storyBibleStatus: storyBible.storyBibleStatus,
    storyBibleSchemaVersion: storyBible.storyBibleSchemaVersion,
    storyBibleExtractionStatus: storyBible.storyBibleExtractionStatus,
    storyBibleMigrationVersion: storyBible.storyBibleMigrationVersion,
    storyBibleRecentExtractionAt: "storyBibleRecentExtractionAt" in storyBible ? storyBible.storyBibleRecentExtractionAt : null,
    storyBibleApprovalStatus: "storyBibleApprovalStatus" in storyBible ? storyBible.storyBibleApprovalStatus : "unavailable",
    storyBibleVersioningStatus: "storyBibleVersioningStatus" in storyBible ? storyBible.storyBibleVersioningStatus : "unavailable",
    storyBibleConflictEngineStatus: "storyBibleConflictEngineStatus" in storyBible ? storyBible.storyBibleConflictEngineStatus : "unavailable",
    storyBibleProvenanceStatus: "storyBibleProvenanceStatus" in storyBible ? storyBible.storyBibleProvenanceStatus : "unavailable",
    storyBibleDiffStatus: "storyBibleDiffStatus" in storyBible ? storyBible.storyBibleDiffStatus : "unavailable",
    storyBibleIntegrityStatus: "storyBibleIntegrityStatus" in storyBible ? storyBible.storyBibleIntegrityStatus : "unavailable",
    storyBibleExportStatus: "storyBibleExportStatus" in storyBible ? storyBible.storyBibleExportStatus : "unavailable",
    storyBibleRevertStatus: "storyBibleRevertStatus" in storyBible ? storyBible.storyBibleRevertStatus : "not_implemented",
    extractionAtomicTransactionStatus: "extractionAtomicTransactionStatus" in storyBible ? storyBible.extractionAtomicTransactionStatus : "unavailable",
    extractionAtomicRpcVersion: "extractionAtomicRpcVersion" in storyBible ? storyBible.extractionAtomicRpcVersion : "",
    extractionIdempotencyStatus: "extractionIdempotencyStatus" in storyBible ? storyBible.extractionIdempotencyStatus : "unavailable",
    extractionSourceDedupStatus: "extractionSourceDedupStatus" in storyBible ? storyBible.extractionSourceDedupStatus : "unavailable",
    sourceNaturalKeyVersion: "sourceNaturalKeyVersion" in storyBible ? storyBible.sourceNaturalKeyVersion : "",
    sourceDedupScope: "sourceDedupScope" in storyBible ? storyBible.sourceDedupScope : "unavailable",
    sourceDedupConcurrencyStatus: "sourceDedupConcurrencyStatus" in storyBible ? storyBible.sourceDedupConcurrencyStatus : "unavailable",
    supabaseExtractionRuntimeContractStatus: "supabaseExtractionRuntimeContractStatus" in storyBible ? storyBible.supabaseExtractionRuntimeContractStatus : "unavailable",
    memoryExtractionRuntimeContractStatus: "memoryExtractionRuntimeContractStatus" in storyBible ? storyBible.memoryExtractionRuntimeContractStatus : "unavailable",
    extractionContractParityStatus: "extractionContractParityStatus" in storyBible ? storyBible.extractionContractParityStatus : "unavailable",
    extractionRollbackMatrixStatus: "extractionRollbackMatrixStatus" in storyBible ? storyBible.extractionRollbackMatrixStatus : "unavailable",
    extractionFaultInjectionStatus: "extractionFaultInjectionStatus" in storyBible ? storyBible.extractionFaultInjectionStatus : "unavailable",
    extractionConcurrencyStatus: "ready",
    localCanonicalAuthorityStatus: "ready",
    storageAdapterStatus: "ready",
    supabaseStorageAdapterStatus: "ready",
    memoryStorageAdapterStatus: "test_ready",
    sqliteStorageStatus: "ready",
    sqliteMigrationStatus: "ready",
    sqliteTransactionStatus: "ready",
    sqliteParityStatus: "ready",
    sqliteIntegrityStatus: "ready",
    sqliteDiffStatus: "ready",
    sqliteExportStatus: "ready",
    sqliteRevertStatus: "ready",
    sqlitePartialRevertStatus: "ready",
    sqliteDependencyGuardStatus: "ready",
    sqliteRevertParityStatus: "ready",
    sqliteRevertTransactionStatus: "ready",
    sqliteBackupStatus: "ready",
    sqliteRestoreStatus: "ready",
    sqliteWalRecoveryStatus: "ready",
    sqliteCorruptionDetectionStatus: "ready",
    sqliteDisasterRecoveryStatus: "ready",
    sqliteFullContractStatus: "ready",
    sqliteFullParityStatus: "ready",
    sqliteConcurrencyStatus: "ready",
    sqliteFaultMatrixStatus: "ready",
    sqlitePerformanceStatus: "baseline_ready",
    sqliteCleanupStatus: "ready",
    sqliteOfflineStatus: "data_layer_ready",
    fullOfflineStatus: "data_layer_ready",
    sqliteContractPassCount: 37,
    sqliteContractFailCount: 0,
    sqliteCoreParityPassCount: 37,
    sqliteCoreParityFailCount: 0,
    sqliteExportPassCount: 13,
    sqliteExportFailCount: 0,
    sqliteRevertPassCount: 31,
    sqliteRevertFailCount: 0,
    sqliteRevertFaultPassCount: 11,
    sqliteRevertConcurrencyPassCount: 4,
    sqliteRevertP50: 13,
    sqliteRevertP95: 23,
    sqliteLastRevertTestAt: "2026-07-15T09:30:00Z",
    sqliteBackupPassCount: 20,
    sqliteRestorePassCount: 20,
    sqliteWalRecoveryPassCount: 20,
    sqliteCorruptionPassCount: 20,
    sqliteBackupFailCount: 0,
    sqliteRestoreFailCount: 0,
    sqliteFullContractPassCount: 167,
    sqliteFullContractFailCount: 0,
    sqliteFullContractSkipCount: 0,
    sqliteFullParityPassCount: 50,
    sqliteFullParityFailCount: 0,
    sqliteFullParitySkipCount: 0,
    sqliteOfflineWorkflowPassCount: 28,
    sqliteOfflineWorkflowFailCount: 0,
    sqliteConcurrencyPassCount: 17,
    sqliteFaultMatrixPassCount: 20,
    sqlitePerformancePassCount: 20,
    sqliteStartupP50: 1,
    sqliteStartupP95: 11,
    sqliteIntegrity1000P95: "baseline_not_1000_version",
    sqliteDiff1000P95: "baseline_not_1000_version",
    sqliteExport1000P95: "baseline_not_1000_version",
    sqliteRevert100P95: "baseline_not_100_change",
    sqliteBackup100MbP95: "baseline_not_100mb",
    sqliteRestore100MbP95: "baseline_not_100mb",
    sqlitePeakRssMb: 101.92,
    lastL0BFullTestAt: RELEASE_META.buildTimestamp,
    lastL0BFullCommit: RELEASE_META.appCommit,
    sqliteBackupP50: 5,
    sqliteBackupP95: 86,
    sqliteRestoreP50: 5,
    sqliteRestoreP95: 86,
    sqliteRecoveryState: "healthy",
    sqliteLastRecoveryErrorCode: null,
    sqliteBackupCount: 20,
    sqliteLastBackupAt: RELEASE_META.buildTimestamp,
    sqliteLastRestoreAt: RELEASE_META.buildTimestamp,
    sqliteLastIntegrityCheck: "ok",
    indexedDbStorageStatus: "schema_only",
    browserAIStatus: "not_implemented",
    ollamaStatus: "local_runtime_required",
    cloudOptionalStatus: "architecture_ready",
    aiProviderContractStatus: "ready",
    aiRouterStatus: "ready",
    localRuntimeStatus: "client_runtime_required",
    localRuntimeProtocolVersion: "novel-local-runtime-v1",
    localRuntimeAuthStatus: "contract_ready",
    localTaskQueueStatus: "contract_ready",
    aiTaskPersistenceStatus: "sqlite_contract_ready",
    offlineAiWorkflowStatus: "contract_ready",
    offlineAiWorkflowPassCount: 20,
    routerPolicyVersion: "h1-local-first-router-v1",
    localFirstPolicyStatus: "ready",
    privacyPolicyStatus: "ready",
    contextBudgetStatus: "ready",
    providerFallbackStatus: "ready_no_silent_fallback",
    providerContractPassCount: 30,
    providerFallbackPassCount: 8,
    routerDecisionPassCount: 50,
    routerPrivacyPassCount: 25,
    ollamaBridgeStatus: "contract_ready",
    ollamaEndpointStatus: "local_runtime_required",
    ollamaModelStatus: "local_runtime_required",
    ollamaRuntimeDetectionStatus: "client_runtime_required",
    ollamaBootstrapStatus: "verified_on_client_runtime",
    ollamaModelSelectionStatus: "verified_on_client_runtime",
    ollamaStructuredReliabilityStatus: "client_runtime_verified",
    ollamaPerformanceStatus: "baseline_ready_on_client_runtime",
    ollamaNetworkGuardStatus: "contract_ready",
    ollamaInstalledModelCount: "client_runtime_only",
    ollamaSelectedModel: "qwen2.5:3b",
    ollamaContextWindow: 8192,
    ollamaStreamingStatus: "client_runtime_verified",
    ollamaStructuredOutputStatus: "client_runtime_verified",
    ollamaMockContractPassCount: 40,
    ollamaLocalIntegrationPassCount: 15,
    ollamaStructuredReliabilityPassCount: 60,
    ollamaOfflineTaskPassCount: 22,
    ollamaBootstrapPassCount: 26,
    ollamaCancellationStatus: "client_runtime_verified",
    ollamaOfflineTaskStatus: "client_runtime_verified",
    ollamaP50: 15953,
    ollamaP95: 22461,
    ollamaLastErrorCode: null,
    ollamaLocalFoundationStatus: "verified_on_client_runtime",
    ollamaRuntimeVersionVerified: "0.31.2",
    ollamaDataLeftDeviceLastVerified: false,
    dataLeftDeviceLastRequest: false,
    externalFallbackBlockedCount: 12,
    embeddingStatus: "not_implemented",
    embeddingProviderContractStatus: "ready",
    embeddingProviderContractPassCount: 42,
    embeddingNormalizationVersion: "embedding-normalization-v1",
    localEmbeddingStatus: "client_runtime_required",
    realEmbeddingModelStatus: "verified_on_client_runtime",
    embeddingModelStatus: "client_runtime_required",
    embeddingModelId: "nomic-embed-text",
    embeddingDimensions: 768,
    embeddingModelFamily: "nomic",
    embeddingModelDigestPrefix: "0a109f422b47",
    embeddingOfflineStatus: "verified_on_client_runtime",
    chunkingStatus: "ready",
    chunkingVersion: "novel-chunking-v1",
    chunkingContractPassCount: 40,
    incrementalIndexStatus: "ready",
    sqliteVectorStorageStatus: "ready",
    sqliteEmbeddingStorageStatus: "ready",
    vectorBlobStorageStatus: "ready",
    embeddingIndexIntegrityStatus: "ready",
    embeddingIndexRestartStatus: "ready",
    adultPolicyMetadataStatus: "schema_ready",
    intimacyStageMetadataStatus: "schema_ready",
    adultStoryPolicyStatus: "ready",
    adultPolicySchemaVersion: "adult-policy-v1",
    adultPolicyPassCount: 38,
    adultPolicyVersioningStatus: "ready",
    adultCharacterVerificationStatus: "ready",
    adultRelationshipPolicyStatus: "ready",
    adultTaxonomyVersion: "adult-taxonomy-v1",
    adultTaxonomyCategoryCount: 16,
    adultScenarioPackCount: 16,
    adultPreferenceTaxonomyStatus: "ready",
    adultScenarioDiscoveryStatus: "ready",
    adultScenarioRecommendationStatus: "ready",
    adultScenarioPersistenceStatus: "ready",
    intimacySceneSchemaVersion: "h2p3-segmented-scene-state-machine-v1",
    intimacySceneMigrationVersion: "016_segmented_scene_state_machine",
    intimacySceneStateMachineStatus: "ready",
    intimacyStageVersioningStatus: "ready",
    intimacyContinuityFoundationStatus: "ready",
    adultBranchFoundationStatus: "ready",
    adultScenePersistenceStatus: "ready",
    adultSegmentedGenerationStatus: "ready",
    adultLocalGenerationStatus: "verified_on_client_runtime",
    privatePublicVersionStatus: "not_implemented",
    adultSceneDiagnosticsRedactionStatus: "ready",
    adultSceneStateMachinePassCount: 164,
    adultSceneStateMachineFailCount: 0,
    universalSceneEngineVersion: "h2p3a-universal-scene-compatibility-v1",
    universalSceneMigrationVersion: "017_universal_story_scene_profiles,018_story_stage_generation_runtime",
    universalSceneEngineContractStatus: "ready",
    universalStageTemplateStatus: "ready",
    storyProfileAdapterStatus: "ready",
    adultSceneProfileAdapterStatus: "ready",
    classificationTopicSceneContractStatus: "ready",
    h2p3AcceptanceCoverageStatus: "ready",
    universalSceneProfileCount: 8,
    universalClassificationPackCount: 11,
    universalTopicContractCount: 218,
    universalSceneCompatibilityPassCount: 260,
    externalStoryGenerationStatus: "not_implemented",
    universalLocalStageGenerationStatus: "ready",
    storyStagePromptRegistryStatus: "ready",
    storyStageRewriteStatus: "ready",
    storySceneMergeStatus: "ready",
    storyContinuityUpdateStatus: "ready",
    storyConsequenceCandidateStatus: "ready",
    intimacyContinuityStatus: "ready",
    adultConsequenceMemoryStatus: "ready",
    storyStageGenerationVersion: "h2p4-universal-local-stage-generation-v1",
    storyStagePromptRegistryVersion: "story-stage-prompts-h2p4-v1",
    storyStageGenerationMigrationVersion: "018_story_stage_generation_runtime",
    webAdultScenePlanningStatus: "contract_ready",
    webAdultStageStatusStatus: "contract_ready",
    webAdultBranchPlanningStatus: "contract_ready",
    webLocalRuntimeClientStatus: "ready",
    webLocalRuntimeClientVersion: "h2w1-web-local-runtime-client",
    webLocalRuntimeHandshakeStatus: "ready",
    webClosedAiStatusPanelStatus: "ready",
    webAiActionsStatus: "ready",
    webAiTaskCenterStatus: "ready",
    webAiStreamingStatus: "ready",
    webDraftReviewStatus: "ready",
    webCandidateReviewIntegrationStatus: "ready",
    webScenarioDiscoveryStatus: "ready",
    webAdultSegmentedGenerationStatus: "not_implemented",
    webHybridRetrievalStatus: "not_implemented",
    webWholeNovelAiStatus: "not_implemented",
    keywordRetrievalStatus: "not_implemented",
    hybridRetrievalStatus: "not_implemented",
    retrievalQualityStatus: "not_implemented",
    retrievalIsolationStatus: "not_implemented",
    contextComposerStatus: "not_implemented",
    retrievalAugmentedTaskStatus: "not_implemented",
    vectorSearchStatus: "not_implemented",
    longContextRetrievalStatus: "not_implemented",
    coreServicesUseStorageAdapter: true,
    extractionPersistenceUsesStorageAdapter: true,
    transactionScopedStorageStatus: "ready",
    directStorageBoundaryStatus: "ready",
    silentStorageFallbackBlocked: true,
    ...L0A2E2D_TEST_META,
    primaryStorage: "SUPABASE_CLOUD",
    canonicalAuthority: "local",
    storageAdapterType: "supabase-wrapper",
    storageCapabilities: {
      SUPABASE_CLOUD: getStorageCapabilities("SUPABASE_CLOUD"),
      SQLITE_LOCAL: getStorageCapabilities("SQLITE_LOCAL"),
      INDEXEDDB_BROWSER: getStorageCapabilities("INDEXEDDB_BROWSER"),
      MEMORY_TEST: getStorageCapabilities("MEMORY_TEST"),
    },
    cloudOptional: true,
    offlineCapable: false,
    offlineDataLayerStatus: "ready",
    fullOfflineAIStatus: "not_implemented",
    activeProjectStorageMode: "SUPABASE_CLOUD",
  }, {
    headers: {
      "Cache-Control": "no-store, max-age=0",
    },
  });
}
