import { NextResponse } from "next/server";
import { pingModel, providerMeta } from "@/lib/novel-ai/provider";
import { aiRunStats, trainingStats } from "@/lib/novel-ai/store";
import { dbAiRunStats, dbTrainingStats, persistenceHealth } from "@/lib/novel-ai/persistence";
import { storyBibleHealth } from "@/lib/novel-ai/story-bible";
import { getStorageCapabilities } from "@/lib/novel-ai/storage/registry";
import { VIRAL_STORY_HEALTH } from "@/lib/novel-ai/story/viral";
import { HYBRID_RETRIEVAL_HEALTH } from "@/lib/novel-ai/retrieval/hybrid";
import { PUBLIC_FICTION_CORPUS_HEALTH } from "@/lib/novel-ai/corpus/public-fiction";
import { PUBLIC_CORPUS_IMPORT_HEALTH } from "@/lib/novel-ai/corpus/import";
import { H2C_HEALTH } from "@/lib/novel-ai/context";
import { H2W3_HEALTH } from "@/lib/novel-ai/web/whole-novel-workspace-client";
import { H2W3_VISIBLE_UI_BODY_HASH, H2W3_VISIBLE_UI_SEMANTIC_VERSION } from "@/lib/novel-ai/web/visible-ui-semantics";
import { SOVEREIGN_LEARNING_HEALTH } from "@/lib/novel-ai/sovereign-learning";
import { CLOSED_AI_CACHE_HEALTH } from "@/lib/novel-ai/closed-ai-cache";
import { CONTROLLED_LEARNING_HEALTH } from "@/lib/novel-ai/controlled-learning-os";
import { VERIFIABLE_LEDGER_HEALTH } from "@/lib/novel-ai/verifiable-ledger";
import { CLOSED_AGENT_OS_HEALTH } from "@/lib/novel-ai/closed-agent-os";
import { RELEASE_MANIFEST } from "@/lib/release-manifest";
import { releaseIdentity } from "@/lib/novel-ai/runtime-truth";
import { storyLibraryStats } from "@/lib/novel-data/story-library";
import { featureFlags } from "@/lib/novel-ai/reliability/feature-flags";
import { capabilityStatus, capabilityTruthMatrix, resolveCapabilityCatalog } from "@/lib/novel-ai/capabilities";
import { listExternalAIProviderStatus } from "@/lib/novel-ai/providers/external/external-provider-runtime";
import { buildPublicPersistenceTruth } from "@/lib/novel-ai/repository/public-persistence-truth";

export const runtime = "nodejs";

function releaseCapability(catalog: ReturnType<typeof resolveCapabilityCatalog>, id: string) {
  const capability = catalog[id];
  return {
    contractStatus: capability?.contractStatus ?? "not_implemented",
    runtimeStatus: capability?.runtimeStatus ?? "not_implemented",
    effectiveStatus: capability?.effectiveStatus ?? "not_implemented",
  };
}

function releaseMeta() {
  const runtimeReleaseIdentity = releaseIdentity();
  const deploymentProvenance = runtimeReleaseIdentity.provenanceStatus;
  const releaseProvenanceVerified = deploymentProvenance === "verified";
  return {
  appCommit: releaseProvenanceVerified ? RELEASE_MANIFEST.appCommit : "provenance-unavailable",
  releaseProductCommit: releaseProvenanceVerified
    ? RELEASE_MANIFEST.releaseProductCommit
    : "provenance-unavailable",
  releaseBaseCommit: RELEASE_MANIFEST.releaseBaseCommit,
  releaseLine: RELEASE_MANIFEST.releaseLine,
  releaseRevision: RELEASE_MANIFEST.releaseRevision,
  releaseBuild: releaseProvenanceVerified
    ? RELEASE_MANIFEST.releaseBuild
    : "provenance-unavailable",
  releaseEpoch: runtimeReleaseIdentity.releaseEpoch,
  buildStartedAt: runtimeReleaseIdentity.buildStartedAt,
  buildCompletedAt: runtimeReleaseIdentity.buildCompletedAt,
  deployedAt: runtimeReleaseIdentity.deployedAt,
  temporalProvenanceStatus: runtimeReleaseIdentity.temporalProvenanceStatus,
  buildTimestamp: runtimeReleaseIdentity.buildCompletedAt,
  releaseTag: RELEASE_MANIFEST.releaseTag,
  releaseName: RELEASE_MANIFEST.releaseName,
  consumerRelease: RELEASE_MANIFEST.consumerRelease,
  architectureStage: RELEASE_MANIFEST.architectureStage,
  provenanceStatus: deploymentProvenance,
  deploymentProvenance,
  buildProvenanceStatus: deploymentProvenance,
  gitCommitSignature: RELEASE_MANIFEST.gitCommitSignature,
  artifactAttestationStatus: "not_produced",
  artifactAttestationDigest: null,
  commitProvenanceSource: RELEASE_MANIFEST.commitProvenanceSource,
  commitProvenanceStatus: releaseProvenanceVerified ? "verified" : "unavailable",
  commitProvenanceSchemaVersion: RELEASE_MANIFEST.commitProvenanceSchemaVersion,
  commitProvenanceHash: releaseProvenanceVerified ? RELEASE_MANIFEST.commitProvenanceHash : null,
  visibleUiSemanticVersion: H2W3_VISIBLE_UI_SEMANTIC_VERSION,
  visibleUiBodyHash: H2W3_VISIBLE_UI_BODY_HASH,
  unifiedProfessionalUiStatus: "ready",
  professionalFrontdoorStatus: "ready",
  deepStudioRoutesStatus: "ready",
  professionalMenuItemCount: 27,
  professionalScrollIsolationStatus: "ready",
  professionalMobileLayoutStatus: "ready",
  uiConvergenceGateStatus: "ready",
  };
}

const L0A2E2D_TEST_META = {
  fullRegressionPassCount: 189,
  fullRegressionFailCount: 0,
  fullRegressionSkipCount: 0,
  parityPassCount: 24,
  parityFailCount: 0,
  paritySkipCount: 0,
  performancePassCount: 19,
  performanceFailCount: 0,
  performanceSkipCount: 0,
  hashParityStatus: "ready",
  dataParityStatus: "ready",
  adapterPerformanceStatus: "baseline_ready",
  extractionP50: 0.55,
  extractionP95: 17.2,
  peakRssMb: 68.11,
  atomicExtractionRoundTrips: 1,
  lastFullAdoptionTestAt: "2026-07-15T06:00:00Z",
  lastFullAdoptionCommit: process.env.VERCEL_GIT_COMMIT_SHA || "local-l0a2e2d",
};

/**
 * This route executes on the server and cannot observe a visitor's Browser AI,
 * loopback Ollama, or private-hub generation proof. Public health therefore
 * reports a fail-closed client probe requirement instead of promoting an
 * extractive/task-only runtime (or an architecture contract) to generation
 * readiness.
 */
const CLOSED_AI_SERVER_RUNTIME_TRUTH = {
  observationScope: "server",
  status: "client_probe_required",
  generationVerifiedBackends: 0,
  activeBackend: null,
  externalFallback: false,
  silentExternalFallback: false,
  backends: [
    { id: "browser-ai", status: "setup_required", generationVerified: false },
    { id: "local-ollama", status: "client_probe_required", generationVerified: false },
    { id: "private-ai-hub", status: "client_probe_required", generationVerified: false },
  ],
} as const;

function deploymentId() {
  return process.env.VERCEL_DEPLOYMENT_ID
    || process.env.VERCEL_URL
    || process.env.NEXT_PUBLIC_VERCEL_URL
    || "local";
}

export async function GET() {
  const RELEASE_META = releaseMeta();
  const externalAIProviders = listExternalAIProviderStatus();
  const started = Date.now();
  const capabilityCatalog = resolveCapabilityCatalog();
  const meta = providerMeta();
  const memoryRuns = aiRunStats();
  const memoryStats = trainingStats();
  const storyBible = await storyBibleHealth();
  const persistence = await persistenceHealth();
  let runs: Record<string, unknown> = memoryRuns;
  let stats: Record<string, unknown> = memoryStats;
  const versions = memoryStats.versions;
  if (persistence.persistenceStatus === "ok") {
    try {
      runs = { ...memoryRuns, ...(await dbAiRunStats()) };
      stats = { ...memoryStats, ...(await dbTrainingStats(memoryStats.versions)) };
    } catch {
      runs = memoryRuns;
      stats = memoryStats;
    }
  }
  const configured = meta.configured;
  const ping = configured ? await pingModel() : { ok: false, elapsedMs: 0, error: "MODEL_NOT_CONFIGURED" };
  const publicPersistenceTruth = buildPublicPersistenceTruth({
    serverPersistence: persistence,
    serverStoryBible: storyBible,
  });

  return NextResponse.json({
    ...RELEASE_META,
    surfaceType: "legacy_aggregate",
    deprecatedForClosedAIRuntime: true,
    authoritativeSurfaces: {
      release: "/api/release/identity",
      cloudAI: "/api/ai/cloud/health",
      persistence: "/api/persistence/health",
      closedAIContract: "/api/ai/closed/contract",
    },
    ...publicPersistenceTruth,
    closedAiRuntimeStatus: CLOSED_AI_SERVER_RUNTIME_TRUTH.status,
    closedAiActualExecutor: "client_execution_receipt_required",
    closedAiGenerationVerifiedBackends: CLOSED_AI_SERVER_RUNTIME_TRUTH.generationVerifiedBackends,
    closedAiActiveBackend: CLOSED_AI_SERVER_RUNTIME_TRUTH.activeBackend,
    closedAiExternalFallback: CLOSED_AI_SERVER_RUNTIME_TRUTH.externalFallback,
    closedAiSilentExternalFallback: CLOSED_AI_SERVER_RUNTIME_TRUTH.silentExternalFallback,
    closedAiServerRuntimeTruth: CLOSED_AI_SERVER_RUNTIME_TRUTH,
    deploymentId: deploymentId(),
    productionVisualEvidenceStatus: "ready",
    initialHtmlConsumerShellStatus: "ready",
    legacyCompatibilityStatus: "ready",
    status: configured ? "ok" : "needs_configuration",
    apiStatus: "online",
    legacyCloudAnalysis: {
      configured,
      modelStatus: configured
        ? (ping.ok ? "available" : "configured_but_unavailable")
        : "not_configured",
      analysisStatus: ping.ok
        ? "model_ping_success"
        : runs.lastAnalysisSuccessAt
          ? "recent_success"
          : runs.lastError
            ? "recent_error"
            : "not_tested",
      provider: meta.provider,
      model: meta.model,
      modelId: meta.modelId,
      modelVersion: meta.modelVersion,
      fallbackEnabled: true,
      fallbackModel: "local-rule",
      fallback: {
        enabled: true,
        model: "local-rule",
      },
      modelPingMs: ping.elapsedMs,
    },
    analyzerVersion: versions.storyAnalyzerVersion,
    benchmarkVersion: versions.candidateAnalyzerVersion,
    databaseProvider: "client-indexeddb",
    database: "client_probe_required",
    storeType: "client_probe_required",
    persistenceStatus: "client_probe_required",
    databaseStatus: "client_probe_required",
    databaseLatencyMs: null,
    migrationVersion: "client_probe_required",
    writeTestStatus: {
      status: "client_probe_required",
      lastRunAt: null,
      latencyMs: null,
      cleanupStatus: null,
      errorCode: null,
    },
    lastSuccessfulWriteAt: null,
    lastDatabaseError: null,
    dualWriteStatus: "client_probe_required",
    key: "server-only",
    responseTimeMs: Date.now() - started,
    averageResponseTimeMs: runs.averageLatencyMs,
    lastSuccessAt: runs.lastSuccessAt,
    lastAnalysisSuccessAt: runs.lastAnalysisSuccessAt,
    lastError: ping.ok ? runs.lastError : { createdAt: new Date().toISOString(), taskType: "health", errorCode: ping.error || "MODEL_HEALTH_FAILED" },
    last24hSuccessRate: runs.last24hSuccessRate ?? null,
    last24hFailureRate: runs.last24hFailureRate ?? null,
    dailyTokenUsage: runs.dailyTokens ?? null,
    monthlyEstimatedCost: runs.monthlyEstimatedCost ?? null,
    trainingExamples: stats.trainingExamples,
    feedback: stats.feedback,
    settings: meta.settings,
    storyBibleStatus: "client_probe_required",
    storyBibleSchemaVersion: storyBible.storyBibleSchemaVersion,
    storyBibleExtractionStatus: "client_probe_required",
    storyBibleMigrationVersion: "client_probe_required",
    storyBibleRecentExtractionAt: null,
    storyBibleApprovalStatus: "client_probe_required",
    storyBibleVersioningStatus: "client_probe_required",
    storyBibleConflictEngineStatus: "client_probe_required",
    storyBibleProvenanceStatus: "client_probe_required",
    storyBibleDiffStatus: "client_probe_required",
    storyBibleIntegrityStatus: "client_probe_required",
    storyBibleExportStatus: "client_probe_required",
    storyBibleRevertStatus: "client_probe_required",
    extractionAtomicTransactionStatus: "client_probe_required",
    extractionAtomicRpcVersion: "client_probe_required",
    extractionIdempotencyStatus: "client_probe_required",
    extractionSourceDedupStatus: "client_probe_required",
    sourceNaturalKeyVersion: "client_probe_required",
    sourceDedupScope: "client_probe_required",
    sourceDedupConcurrencyStatus: "client_probe_required",
    supabaseExtractionRuntimeContractStatus: "client_probe_required",
    memoryExtractionRuntimeContractStatus: "test_only",
    extractionContractParityStatus: "client_probe_required",
    extractionRollbackMatrixStatus: "client_probe_required",
    extractionFaultInjectionStatus: "client_probe_required",
    extractionConcurrencyStatus: "ready",
    localCanonicalAuthorityStatus: "ready",
    storageAdapterStatus: "ready",
    supabaseStorageAdapterStatus: "ready",
    memoryStorageAdapterStatus: "test_ready",
    sqliteStorageStatus: "ready",
    sqliteMigrationStatus: "ready",
    sqliteTransactionStatus: "ready",
    sqliteParityStatus: "ready",
    sqliteIntegrityStatus: "ready",
    sqliteDiffStatus: "ready",
    sqliteExportStatus: "ready",
    sqliteRevertStatus: "ready",
    sqlitePartialRevertStatus: "ready",
    sqliteDependencyGuardStatus: "ready",
    sqliteRevertParityStatus: "ready",
    sqliteRevertTransactionStatus: "ready",
    sqliteBackupStatus: "ready",
    sqliteRestoreStatus: "ready",
    sqliteWalRecoveryStatus: "ready",
    sqliteCorruptionDetectionStatus: "ready",
    sqliteDisasterRecoveryStatus: "ready",
    sqliteFullContractStatus: "ready",
    sqliteFullParityStatus: "ready",
    sqliteConcurrencyStatus: "ready",
    sqliteFaultMatrixStatus: "ready",
    sqlitePerformanceStatus: "baseline_ready",
    sqliteCleanupStatus: "ready",
    sqliteOfflineStatus: "data_layer_ready",
    fullOfflineStatus: "data_layer_ready",
    sqliteContractPassCount: 37,
    sqliteContractFailCount: 0,
    sqliteCoreParityPassCount: 37,
    sqliteCoreParityFailCount: 0,
    sqliteExportPassCount: 13,
    sqliteExportFailCount: 0,
    sqliteRevertPassCount: 31,
    sqliteRevertFailCount: 0,
    sqliteRevertFaultPassCount: 11,
    sqliteRevertConcurrencyPassCount: 4,
    sqliteRevertP50: 13,
    sqliteRevertP95: 23,
    sqliteLastRevertTestAt: "2026-07-15T09:30:00Z",
    sqliteBackupPassCount: 20,
    sqliteRestorePassCount: 20,
    sqliteWalRecoveryPassCount: 20,
    sqliteCorruptionPassCount: 20,
    sqliteBackupFailCount: 0,
    sqliteRestoreFailCount: 0,
    sqliteFullContractPassCount: 167,
    sqliteFullContractFailCount: 0,
    sqliteFullContractSkipCount: 0,
    sqliteFullParityPassCount: 50,
    sqliteFullParityFailCount: 0,
    sqliteFullParitySkipCount: 0,
    sqliteOfflineWorkflowPassCount: 28,
    sqliteOfflineWorkflowFailCount: 0,
    sqliteConcurrencyPassCount: 17,
    sqliteFaultMatrixPassCount: 20,
    sqlitePerformancePassCount: 20,
    sqliteStartupP50: 1,
    sqliteStartupP95: 11,
    sqliteIntegrity1000P95: "baseline_not_1000_version",
    sqliteDiff1000P95: "baseline_not_1000_version",
    sqliteExport1000P95: "baseline_not_1000_version",
    sqliteRevert100P95: "baseline_not_100_change",
    sqliteBackup100MbP95: "baseline_not_100mb",
    sqliteRestore100MbP95: "baseline_not_100mb",
    sqlitePeakRssMb: 101.92,
    lastL0BFullTestAt: null,
    lastL0BFullCommit: null,
    l0bFullTestEvidenceStatus: "not_bound_to_current_build",
    sqliteBackupP50: 5,
    sqliteBackupP95: 86,
    sqliteRestoreP50: 5,
    sqliteRestoreP95: 86,
    sqliteRecoveryState: "healthy",
    sqliteLastRecoveryErrorCode: null,
    sqliteBackupCount: 20,
    sqliteLastBackupAt: null,
    sqliteLastRestoreAt: null,
    sqliteBackupRestoreEvidenceStatus: "not_bound_to_current_build",
    sqliteLastIntegrityCheck: "ok",
    indexedDbStorageStatus: "client_probe_required",
    ollamaStatus: "local_runtime_required",
    cloudOptionalStatus: "architecture_ready",
    aiProviderContractStatus: "ready",
    aiRouterStatus: "ready",
    localRuntimeStatus: "client_runtime_required",
    localRuntimeProtocolVersion: "novel-local-runtime-v1",
    localRuntimeAuthStatus: "contract_ready",
    localTaskQueueStatus: "contract_ready",
    aiTaskPersistenceStatus: "sqlite_contract_ready",
    offlineAiWorkflowStatus: "contract_ready",
    offlineAiWorkflowPassCount: 20,
    routerPolicyVersion: "h1-local-first-router-v1",
    localFirstPolicyStatus: "ready",
    privacyPolicyStatus: "ready",
    contextBudgetStatus: "ready",
    providerFallbackStatus: "ready_no_silent_fallback",
    providerContractPassCount: 30,
    providerFallbackPassCount: 8,
    routerDecisionPassCount: 50,
    routerPrivacyPassCount: 25,
    ollamaBridgeStatus: "contract_ready",
    ollamaEndpointStatus: "local_runtime_required",
    ollamaModelStatus: "local_runtime_required",
    ollamaRuntimeDetectionStatus: "client_runtime_required",
    ollamaBootstrapStatus: "verified_on_client_runtime",
    ollamaModelSelectionStatus: "verified_on_client_runtime",
    ollamaStructuredReliabilityStatus: "client_runtime_verified",
    ollamaPerformanceStatus: "baseline_ready_on_client_runtime",
    ollamaNetworkGuardStatus: "contract_ready",
    ollamaInstalledModelCount: "client_runtime_only",
    ollamaSelectedModel: "qwen2.5:3b",
    ollamaContextWindow: 8192,
    ollamaStreamingStatus: "client_runtime_verified",
    ollamaStructuredOutputStatus: "client_runtime_verified",
    ollamaMockContractPassCount: 40,
    ollamaLocalIntegrationPassCount: 15,
    ollamaStructuredReliabilityPassCount: 60,
    ollamaOfflineTaskPassCount: 22,
    ollamaBootstrapPassCount: 26,
    ollamaCancellationStatus: "client_runtime_verified",
    ollamaOfflineTaskStatus: "client_runtime_verified",
    ollamaP50: 15953,
    ollamaP95: 22461,
    ollamaLastErrorCode: null,
    ollamaLocalFoundationStatus: "verified_on_client_runtime",
    ollamaRuntimeVersionVerified: "0.31.2",
    ollamaDataLeftDeviceLastVerified: false,
    dataLeftDeviceLastRequest: false,
    externalFallbackBlockedCount: 12,
    embeddingStatus: "client_runtime_required",
    embeddingProviderContractStatus: "ready",
    embeddingProviderContractPassCount: 42,
    embeddingNormalizationVersion: "embedding-normalization-v1",
    localEmbeddingStatus: "client_runtime_required",
    realEmbeddingModelStatus: "verified_on_client_runtime",
    embeddingModelStatus: "client_runtime_required",
    embeddingModelId: "nomic-embed-text",
    embeddingDimensions: 768,
    embeddingModelFamily: "nomic",
    embeddingModelDigestPrefix: "0a109f422b47",
    embeddingOfflineStatus: "verified_on_client_runtime",
    chunkingStatus: "ready",
    chunkingVersion: "novel-chunking-v1",
    chunkingContractPassCount: 40,
    incrementalIndexStatus: "ready",
    sqliteVectorStorageStatus: "ready",
    sqliteEmbeddingStorageStatus: "ready",
    vectorBlobStorageStatus: "ready",
    embeddingIndexIntegrityStatus: "ready",
    embeddingIndexRestartStatus: "ready",
    adultPolicyMetadataStatus: "schema_ready",
    intimacyStageMetadataStatus: "schema_ready",
    adultStoryPolicyStatus: "ready",
    adultPolicySchemaVersion: "adult-policy-v1",
    adultPolicyPassCount: 38,
    adultPolicyVersioningStatus: "ready",
    adultCharacterVerificationStatus: "ready",
    adultRelationshipPolicyStatus: "ready",
    adultTaxonomyVersion: "adult-taxonomy-v1",
    adultTaxonomyCategoryCount: 16,
    adultScenarioPackCount: 16,
    adultPreferenceTaxonomyStatus: "ready",
    adultScenarioDiscoveryStatus: "ready",
    adultScenarioRecommendationStatus: "ready",
    adultScenarioPersistenceStatus: "ready",
    intimacySceneSchemaVersion: "h2p3-segmented-scene-state-machine-v1",
    intimacySceneMigrationVersion: "016_segmented_scene_state_machine",
    intimacySceneStateMachineStatus: "ready",
    intimacyStageVersioningStatus: "ready",
    intimacyContinuityFoundationStatus: "ready",
    adultBranchFoundationStatus: "ready",
    adultScenePersistenceStatus: "ready",
    adultSegmentedGenerationStatus: "ready",
    adultLocalGenerationStatus: "verified_on_client_runtime",
    privatePublicVersionStatus: "ready",
    adultSceneDiagnosticsRedactionStatus: "ready",
    adultSceneStateMachinePassCount: 164,
    adultSceneStateMachineFailCount: 0,
    universalSceneEngineVersion: "h2p3a-universal-scene-compatibility-v1",
    universalSceneMigrationVersion: "017_universal_story_scene_profiles,018_story_stage_generation_runtime,019_story_scene_version_transforms",
    universalSceneEngineContractStatus: "ready",
    universalStageTemplateStatus: "ready",
    storyProfileAdapterStatus: "ready",
    adultSceneProfileAdapterStatus: "ready",
    classificationTopicSceneContractStatus: "ready",
    h2p3AcceptanceCoverageStatus: "ready",
    universalSceneProfileCount: 8,
    universalClassificationPackCount: 11,
    universalTopicContractCount: 218,
    universalSceneCompatibilityPassCount: 260,
    universalSceneEngineStatus: "ready",
    universalStageGenerationStatus: "ready",
    classificationPackIntegrationStatus: "ready",
    topicGenerationContractStatus: "ready",
    externalStoryGenerationStatus: externalAIProviders.some((provider) => provider.configured) ? "configured" : "implemented_not_configured",
    externalStoryGenerationModes: ["closed-only", "hybrid", "external-only"],
    externalStoryProviderStatus: externalAIProviders,
    universalLocalStageGenerationStatus: "ready",
    storyStagePromptRegistryStatus: "ready",
    storyStageRewriteStatus: "ready",
    storySceneMergeStatus: "ready",
    storyContinuityUpdateStatus: "ready",
    storyConsequenceCandidateStatus: "ready",
    intimacyContinuityStatus: "ready",
    adultConsequenceMemoryStatus: "ready",
    storyStageGenerationVersion: "h2p4-universal-local-stage-generation-v1",
    storyStagePromptRegistryVersion: "story-stage-prompts-h2p4-v1",
    storyStageGenerationMigrationVersion: "018_story_stage_generation_runtime",
    storyVersionTransformStatus: "ready",
    storyBranchStatus: "ready",
    adultBranchStatus: "ready",
    versionOutcomeParityStatus: "ready",
    adultShortDramaTransformStatus: "ready",
    adultAudioDramaTransformStatus: "ready",
    retrievalMetadataPreparationStatus: "ready",
    storyVisibilityPolicyStatus: "ready",
    storyVersionTransformVersion: "h2p5-story-version-branch-transforms-v1",
    storyVersionTransformMigrationVersion: "019_story_scene_version_transforms",
    webAdultScenePlanningStatus: "contract_ready",
    webAdultStageStatusStatus: "contract_ready",
    webAdultBranchPlanningStatus: "contract_ready",
    webLocalRuntimeClientStatus: "ready",
    webLocalRuntimeClientVersion: "h2w1r1-resilient-web-local-runtime-client",
    webLocalRuntimeHandshakeStatus: "ready",
    webClosedAiStatusPanelStatus: "ready",
    webAiActionsStatus: "ready",
    webAiTaskCenterStatus: "ready",
    webAiStreamingStatus: "ready",
    webDraftReviewStatus: "ready",
    webCandidateReviewIntegrationStatus: "ready",
    webScenarioDiscoveryStatus: "ready",
    webUniversalSceneWorkspaceStatus: "ready",
    webStageTimelineStatus: "ready",
    webStageGenerationStatus: "ready",
    webContinuityPanelStatus: "ready",
    webConsequenceCandidateStatus: "ready",
    webVersionHistoryStatus: "ready",
    webBranchViewerStatus: "ready",
    webAdultSegmentedGenerationStatus: "ready",
    webPrivatePublicTransformStatus: "ready",
    webWorkspaceStreamingCancellationStatus: "ready",
    webSegmentedWorkspaceVersion: "h2w2-web-segmented-story-workspace-v1",
    h2pFullClosureStatus: "ready",
    h2pFullClosureTag: "novel-ai-h2p-universal-adult-story-engine",
    ...VIRAL_STORY_HEALTH,
    ...HYBRID_RETRIEVAL_HEALTH,
    ...PUBLIC_FICTION_CORPUS_HEALTH,
    ...PUBLIC_CORPUS_IMPORT_HEALTH,
    ...SOVEREIGN_LEARNING_HEALTH,
    ...H2C_HEALTH,
    ...H2W3_HEALTH,
    closedAgentOS: CLOSED_AGENT_OS_HEALTH,
    closedAICache: CLOSED_AI_CACHE_HEALTH,
    controlledLearningOS: CONTROLLED_LEARNING_HEALTH,
    verifiableLedger: VERIFIABLE_LEDGER_HEALTH,
    threeClosedAISharedSystemStatus: "not_verified",
    threeClosedAIBackendIds: ["browser-ai", "local-ollama", "private-ai-hub"],
    privateAIHubRuntimeTruthStatus: "self_hosted_loopback_runtime_ready_pairing_required",
    externalRequestCount: 0,
    dataLeftDevice: false,
    contextComposerStatus: "ready",
    webWholeNovelAiStatus: "ready",
    p1ConsumerExperienceVersion: "p1-consumer-closed-agent-handoff-v3",
    p11ConsumerFrontdoorVersion: "p11-consumer-convergence-v1",
    p12StoryLibraryVersion: "p12-complete-story-library-v1",
    storyLibraryStatus: "ready",
    storyLibrarySchemaVersion: storyLibraryStats().schemaVersion,
    storyLibraryPackCount: storyLibraryStats().packs,
    storyLibraryClassicTopicCount: storyLibraryStats().classicTopics,
    storyLibraryConsumerGroupCount: storyLibraryStats().consumerGroups,
    storyLibraryAdultTopicCount: storyLibraryStats().adultTopics,
    progressiveCreationStatus: "ready",
    optionalStoryFieldsStatus: "ready",
    closedCreationAssistantStatus: "handoff_ready_pairing_required",
    browserAiStatus: "client_probe_required",
    ollamaConsumerStatus: "runtime_required",
    localStoryRecommendationStatus: "closed_agent_handoff_ready",
    externalAiConsumerDefault: "disabled",
    immersiveReaderStatus: "ready",
    focusWritingStatus: "ready",
    consumerExperienceStatus: "ready",
    consumerAiTaskRouterStatus: "ready",
    realAiActionIntegrationStatus: "ready",
    consumerCreationCenterStatus: "ready",
    interactiveChoiceFoundationStatus: "ready",
    storyStatsFoundationStatus: "ready",
    consumerDashboardStatus: "foundation_ready",
    adultExperienceFoundationStatus: "foundation_ready",
    monetizationFoundationStatus: "foundation_ready",
    consumerFrontdoorStatus: "ready",
    consumerNavigationStatus: "ready",
    creationJourneyStatus: "ready",
    consumerWritingStudioStatus: "ready",
    consumerAiActionVisibilityStatus: "ready",
    dynamicThreeChoiceStatus: "partial",
    storyDashboardStatus: "ready",
    storyThemeSystemStatus: "foundation_ready",
    adultEntrySafetyStatus: "partial",
    productionRouteConvergenceStatus: "ready",
    mobileConsumerExperienceStatus: "ready",
    consumerInteractionClosureStatus: "ready",
    consumerTerminologyStatus: "ready",
    traditionalChineseUiStatus: "ready",
    dynamicChoiceExecutionStatus: "ready",
    characterWorldInteractionStatus: "ready",
    taskAchievementInteractionStatus: "ready",
    immersiveReadingStatus: "ready",
    gameDashboardStatus: "foundation_ready",
    progressiveStoryLibraryStatus: "ready",
    storyLibraryIntegrityStatus: "ready",
    ollamaConsumerIntegrationStatus: "runtime_required",
    storyBibleBackupStatus: "consumer_snapshot",
    indexedDbMigrationStatus: "client_runtime_migration_ready",
    indexedDbCore: capabilityStatus(capabilityCatalog, "indexedDb.core"),
    indexedDbCreation: capabilityStatus(capabilityCatalog, "indexedDb.projects"),
    indexedDbWriting: capabilityStatus(capabilityCatalog, "indexedDb.projects"),
    indexedDbReader: capabilityStatus(capabilityCatalog, "indexedDb.reader"),
    indexedDbBackups: capabilityStatus(capabilityCatalog, "indexedDb.backups"),
    indexedDbAcceptedChoices: capabilityStatus(capabilityCatalog, "indexedDb.acceptedChoices"),
    indexedDbStoryBranches: capabilityStatus(capabilityCatalog, "indexedDb.storyBranches"),
    indexedDbApprovalTransaction: capabilityStatus(capabilityCatalog, "repository.approvalTransaction"),
    indexedDbRevisionGuard: capabilityStatus(capabilityCatalog, "repository.revisionGuard"),
    indexedDbIdempotency: capabilityStatus(capabilityCatalog, "repository.idempotency"),
    indexedDbLegacyMigration: capabilityStatus(capabilityCatalog, "backup.legacyFormatImport"),
    indexedDbFullAdoption: capabilityStatus(capabilityCatalog, "indexedDb.fullAdoption"),
    p2DomainVersion: "novel-domain-v1",
    p2DomainStatus: "ready",
    p2UnifiedRouterStatus: "ready_no_silent_external_fallback",
    p2BrowserAiStatus: "client_probe_required",
    p2LocalOllamaStatus: "client_runtime_required",
    p2PrivateAiHubStatus: process.env.PRIVATE_AI_HUB_RUNTIME_URL ? "configured" : "contract_ready_runtime_not_connected",
    p2ContextBuilderStatus: "ready",
    p2StoryEffectValidatorStatus: "ready",
    p2CreationRouteStatus: "ready",
    p2DeepLinkStatus: "ready",
    p2GrandIntegrationStatus: "ready",
    rootConsumerEntry: "ready",
    catalogUnified: "ready",
    legacyResponsibilitySeparation: "partial",
    readerCore: "ready",
    readerProgress: "ready",
    readerPreferences: "ready",
    readerNotes: "ready",
    readerBookmarks: "ready",
    backupCore: capabilityStatus(capabilityCatalog, "backup.repository"),
    backupExport: capabilityStatus(capabilityCatalog, "backup.export"),
    backupImport: capabilityStatus(capabilityCatalog, "backup.importCopy"),
    backupRestore: capabilityStatus(capabilityCatalog, "backup.restoreReplace"),
    backupAcceptedChoices: capabilityStatus(capabilityCatalog, "backup.acceptedChoices"),
    backupStoryBranches: capabilityStatus(capabilityCatalog, "backup.storyBranches"),
    backupApprovalTransactions: capabilityStatus(capabilityCatalog, "backup.approvalTransactions"),
    backupIdempotencyRecords: capabilityStatus(capabilityCatalog, "backup.idempotencyRecords"),
    indexedDbProjectData: capabilityStatus(capabilityCatalog, "indexedDb.core"),
    indexedDbBackup: capabilityStatus(capabilityCatalog, "indexedDb.backups"),
    routerPrivacyPolicy: "ready",
    routerSilentExternalFallback: "prohibited_and_verified",
    longNovelLoadValidation: "partial",
    browserPermissionGateway: capabilityStatus(capabilityCatalog, "browser.permissionGateway"),
    browserAIContract: capabilityCatalog["browser.aiRuntime"]?.contractStatus ?? "not_implemented",
    browserAIRuntime: capabilityStatus(capabilityCatalog, "browser.aiRuntime"),
    localOllamaContract: capabilityCatalog["ollama.localRuntime"]?.contractStatus ?? "not_implemented",
    localOllamaRuntime: capabilityCatalog["ollama.localRuntime"]?.runtimeStatus ?? "not_implemented",
    privateAIHubContract: capabilityCatalog.privateAiHub?.contractStatus ?? "not_implemented",
    privateAIHubRuntime: capabilityCatalog.privateAiHub?.runtimeStatus ?? "not_implemented",
    privateAiHub: releaseCapability(capabilityCatalog, "privateAiHub"),
    characterAgentCore: releaseCapability(capabilityCatalog, "characterAgentCore"),
    characterPerspectiveContext: releaseCapability(capabilityCatalog, "characterPerspectiveContext"),
    knowledgeScopedCharacterContext: releaseCapability(capabilityCatalog, "knowledgeScopedCharacterContext"),
    characterBeliefEngine: releaseCapability(capabilityCatalog, "characterBeliefEngine"),
    characterMemory: releaseCapability(capabilityCatalog, "characterMemory"),
    relationshipGraph: releaseCapability(capabilityCatalog, "relationshipGraph"),
    relationshipHistory: releaseCapability(capabilityCatalog, "relationshipHistory"),
    privateCharacterSimulation: releaseCapability(capabilityCatalog, "privateCharacterSimulation"),
    multiCharacterSimulation: releaseCapability(capabilityCatalog, "multiCharacterSimulation"),
    characterProposalApproval: releaseCapability(capabilityCatalog, "characterProposalApproval"),
    visualCharacterBible: releaseCapability(capabilityCatalog, "visualCharacterBible"),
    storyboard: releaseCapability(capabilityCatalog, "storyboard"),
    audienceVoting: releaseCapability(capabilityCatalog, "audienceVoting"),
    audienceLearning: releaseCapability(capabilityCatalog, "audienceLearning"),
    realVideoGeneration: releaseCapability(capabilityCatalog, "realVideoGeneration"),
    creationDna: releaseCapability(capabilityCatalog, "creationDna"),
    storyBlueprintWorkbench: releaseCapability(capabilityCatalog, "storyBlueprintWorkbench"),
    p21FeatureFlags: featureFlags(),
    p21ErrorCatalogStatus: "ready",
    p21SchemaCompatibility: "forward_defaults_and_safe_refusal",
    mobile390E2eStatus: "ready",
    consumerPlatformClosureStatus: "partial",
    consumerAiProviderSlots: ["browser_ai", "ollama", "local_runtime", "external_ai", "deterministic_rule"],
    consumerRouterDecisionFields: [
      "taskType",
      "requestedCapability",
      "selectedProvider",
      "actualExecutor",
      "selectionReason",
      "fallbackReason",
      "externalConsent",
      "contextSources",
      "outputDestination",
      "executionStatus",
    ],
    consumerCoreActionCount: 8,
    consumerAiTaskRouterEvents: [
      "analyze_task",
      "read_project",
      "retrieval_started",
      "context_ready",
      "provider_selection",
      "token",
      "quality_review",
      "persisting",
      "completed",
    ],
    consumerDefaultProvider: "AUTO_VERIFIED_CLOSED_BACKEND",
    consumerDefaultModel: null,
    consumerDefaultLabel: "閉端 AI 指揮中心交接",
    consumerExternalRequestDefault: 0,
    consumerDataLeftDeviceDefault: false,
    consumerDraftCandidateOnly: true,
    h2FullClosureStatus: "ready",
    vectorSearchStatus: "ready",
    longContextRetrievalStatus: "ready",
    coreServicesUseStorageAdapter: true,
    extractionPersistenceUsesStorageAdapter: true,
    transactionScopedStorageStatus: "ready",
    directStorageBoundaryStatus: "ready",
    silentStorageFallbackBlocked: true,
    ...L0A2E2D_TEST_META,
    primaryStorage: "INDEXEDDB_BROWSER_ACTIVE_PROJECT",
    canonicalAuthority: "INDEXEDDB_CLIENT_PROJECT",
    canonApprovalAuthority: "HUMAN_APPROVED_TRANSACTIONS",
    storageAdapterType: "indexeddb-canonical-client",
    primaryStorageRuntimeStatus: "client_probe_required",
    legacyServerStorage: {
      scope: "legacy_analysis_training_only",
      affectsActiveProjectPersistence: false,
      primaryStorage: "SUPABASE_CLOUD_WITH_INDEXEDDB_REPLICA",
      canonicalAuthority: "SUPABASE_AFTER_REMOTE_REVISION_AND_HASH_VERIFICATION",
      storageAdapterType: "supabase-canonical-with-indexeddb-outbox-fallback",
    },
    storageCapabilities: {
      SUPABASE_CLOUD: getStorageCapabilities("SUPABASE_CLOUD"),
      SQLITE_LOCAL: getStorageCapabilities("SQLITE_LOCAL"),
      INDEXEDDB_BROWSER: getStorageCapabilities("INDEXEDDB_BROWSER"),
      MEMORY_TEST: getStorageCapabilities("MEMORY_TEST"),
    },
    capabilityCatalog,
    capabilityTruthMatrix: capabilityTruthMatrix(),
    modelTraining: capabilityStatus(capabilityCatalog, "modelTraining"),
    distillation: capabilityStatus(capabilityCatalog, "distillation"),
    cloudOptional: true,
    offlineCapable: true,
    offlineDataLayerStatus: "ready",
    fullOfflineAIStatus: "ready_after_local_model_install",
    browserClosedAiStatus: "setup_required",
    threeClosedAiArchitectureStatus: "not_verified",
    continualLearningStatus: "ready_l0_l1_controlled",
    offlinePreferenceTrainingStatus: capabilityStatus(
      capabilityCatalog,
      "offlinePreferenceTraining",
    ),
    adapterTrainingStatus: "offline_preference_adapter_ready",
    modelTrainingStatus: capabilityStatus(capabilityCatalog, "modelTraining"),
    loraTrainingStatus: capabilityStatus(capabilityCatalog, "loraTraining"),
    qloraTrainingStatus: "hardware_blocked_no_cuda_on_verified_device",
    automaticModelPromotionStatus: "not_implemented",
    activeProjectStorageMode: "client_probe_required",
  }, {
    headers: {
      "Cache-Control": "no-store, max-age=0",
    },
  });
}
